### ISSUE TITLE
Fish 4.0 Mac alt/option+[right/left] doesn't consider adding words

### ISSUE THREAD

**Issue by mathbunnyru** [fish-shell/fish-shell#11192]
Let's say that I typed `cd Doc` and the command `cd Documents/oss/docker-stacks` is in history.

Both fish 3 and fish 4 suggest to autocomplete and it looks like this:

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/82f8a0c8-46cb-427d-80d0-10c991f6bae7" />

Then I press alt/option(on Mac)+right.

The behaviour on fish v3 (which I like), only word `Documents` is completed, the rest is still suggested:

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/27d9b6ed-1393-4018-b946-22a46326af54" />

Fish v4, everything is completed:

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/f9f09aae-921f-4ddc-a7e8-9022804e9cbd" />

Moreover, after everything is completed there is no way to move left/right between words in v4. In fish v3 I was able to use alt/option+left/right and move between command words, in fish v4 it just moves one char left/right.

I'm using:
- macOS 15.3.1
- Apple M2 processor
- fish installed from homebrew
- iTerm2

**Comment by faho** [comment]
What does `bind alt-right` say? How about `echo $version`?

**Comment by mathbunnyru** [comment]
> What does `bind alt-right` say? How about `echo $version`?

`bind --preset alt-right nextd-or-forward-word`

`4.0.0`

**Comment by faho** [comment]
Run `fish_key_reader`, press option-right. What does that say?

What is that key chord bound to (`bind ...`)?

**Comment by mathbunnyru** [comment]
> Run `fish_key_reader`, press option-right. What does that say?
> 
> What is that key chord bound to (`bind ...`)?

```
Press a key:
bind right 'do something'
```

**Comment by mathbunnyru** [comment]
```
bind --preset ctrl-y yank
bind --preset alt-y yank-pop
bind --preset right forward-char
bind --preset left backward-char
bind --preset -k right forward-char
bind --preset -k left backward-char
bind --preset ctrl-right forward-word
bind --preset ctrl-left backward-word
bind --preset pageup beginning-of-history
bind --preset pagedown end-of-history
bind --preset -k ppage beginning-of-history
bind --preset -k npage end-of-history
bind --preset ctrl-x fish_clipboard_copy
bind --preset ctrl-v fish_clipboard_paste
bind --preset escape cancel
bind --preset ctrl-\[ cancel
bind --preset tab complete
bind --preset ctrl-i complete
bind --preset ctrl-s pager-toggle-search
bind --preset shift-tab complete-and-search
bind --preset -k btab complete-and-search
bind --preset shift-delete history-pager-delete or backward-delete-char
bind --preset -k sdc history-pager-delete or backward-delete-char
bind --preset down down-or-search
bind --preset -k down down-or-search
bind --preset up up-or-search
bind --preset -k up up-or-search
bind --preset shift-right forward-bigword
bind --preset shift-left backward-bigword
bind --preset -k sright forward-bigword
bind --preset -k sleft backward-bigword
bind --preset alt-right nextd-or-forward-word
bind --preset alt-left prevd-or-backward-word
bind --preset alt-up history-token-search-backward
bind --preset alt-down history-token-search-forward
bind --preset alt-. history-token-search-backward
bind --preset alt-l __fish_list_current_token
bind --preset alt-o __fish_preview_current_file
bind --preset alt-w __fish_whatis_current_token
bind --preset ctrl-l clear-screen
bind --preset ctrl-c clear-commandline
bind --preset ctrl-u backward-kill-line
bind --preset ctrl-k kill-line
bind --preset ctrl-w backward-kill-path-component
bind --preset end end-of-line
bind --preset home beginning-of-line
bind --preset alt-d 'if test "$(commandline; printf .)" = \\n.; __fish_echo dirh; else; commandline -f kill-word; end'
bind --preset ctrl-d delete-or-exit
bind --preset alt-s 'for cmd in sudo doas please; if command -q $cmd; fish_commandline_prepend $cmd; break; end; end'
bind --preset f1 __fish_man_page
bind --preset -k f1 __fish_man_page
bind --preset alt-h __fish_man_page
bind --preset alt-p __fish_paginate
bind --preset alt-\# __fish_toggle_comment_commandline
bind --preset alt-e edit_command_buffer
bind --preset alt-v edit_command_buffer
bind --preset '' self-insert
bind --preset space self-insert expand-abbr
bind --preset \; self-insert expand-abbr
bind --preset \| self-insert expand-abbr
bind --preset \& self-insert expand-abbr
bind --preset \> self-insert expand-abbr
bind --preset \< self-insert expand-abbr
bind --preset shift-enter 'commandline -i \\n' expand-abbr
bind --preset alt-enter 'commandline -i \\n' expand-abbr
bind --preset \) self-insert expand-abbr
bind --preset ctrl-space 'test -n "$(commandline)" && commandline -i " "'
bind --preset shift-space 'commandline -i " "' expand-abbr
bind --preset enter execute
bind --preset ctrl-j execute
bind --preset ctrl-m execute
bind --preset ctrl-enter execute
bind --preset delete delete-char
bind --preset backspace backward-delete-char
bind --preset shift-backspace backward-delete-char
bind --preset -k home beginning-of-line
bind --preset ctrl-a beginning-of-line
bind --preset ctrl-e end-of-line
bind --preset ctrl-h backward-delete-char
bind --preset ctrl-p up-or-search
bind --preset ctrl-n down-or-search
bind --preset ctrl-f forward-char
bind --preset ctrl-b backward-char
bind --preset ctrl-t transpose-chars
bind --preset ctrl-g cancel
bind --preset ctrl-/ undo
bind --preset ctrl-_ undo
bind --preset ctrl-z undo
bind --preset ctrl-Z redo
bind --preset alt-/ redo
bind --preset alt-t transpose-words
bind --preset alt-u upcase-word
bind --preset alt-c capitalize-word
bind --preset alt-backspace backward-kill-word
bind --preset ctrl-backspace backward-kill-word
bind --preset ctrl-delete kill-word
bind --preset alt-b prevd-or-backward-word
bind --preset alt-f nextd-or-forward-word
bind --preset alt-\< beginning-of-buffer
bind --preset alt-\> end-of-buffer
bind --preset ctrl-r history-pager
bind --preset \e\uF50Eep fish_clipboard_paste
```

**Comment by krobelus** [comment]
which version of iterm? May be https://github.com/fish-shell/fish-shell/issues/11025

**Comment by faho** [comment]
> I ran bind (is that what you needed? Sorry, I don't completely understand what you need):

I mean I meant `bind right`, but it's fine, that info is also contained here.

---

Okay, you're hitting an iterm bug - #11025, which was supposed to be fixed in iTerm 3.5.12, and fish disables the kitty keyboard protocol in iTerm up to that version.

**Comment by faho** [comment]
The easy workaround for now is:

```fish
set -Ua fish_features no-keyboard-protocols
```

But I really want to know if this is either iTerm 3.5.12 and it shipped without the fix, or our version detection is going wrong.

**Comment by krobelus** [comment]
yeah maybe it's some specific nightly version.

**Comment by mathbunnyru** [comment]
> which version of iterm? May be [#11025](https://github.com/fish-shell/fish-shell/issues/11025)

Build 3.5.11, which is the latest stable version of iTerm2: https://iterm2.com/downloads.html

**Comment by mathbunnyru** [comment]
Just so you know, iTerm 3.5.12 has not been yet released, so probably everyone using iTerm2 encounters this issue for now

**Comment by faho** [comment]
What does `set --show LC_TERMINAL LC_TERMINAL_VERSION` say?

**Comment by mathbunnyru** [comment]
> The easy workaround for now is:
> 
> set -Ua fish_features no-keyboard-protocols
> But I really want to know if this is either iTerm 3.5.12 and it shipped without the fix, or our version detection is going wrong.

This helps, thank you so much!

**Comment by mathbunnyru** [comment]
> What does `set --show LC_TERMINAL LC_TERMINAL_VERSION` say?

```
$LC_TERMINAL: set in global scope, exported, with 1 elements
$LC_TERMINAL[1]: |iTerm2|
$LC_TERMINAL: originally inherited as |iTerm2|
$LC_TERMINAL_VERSION: set in global scope, exported, with 1 elements
$LC_TERMINAL_VERSION[1]: |3.5.11|
$LC_TERMINAL_VERSION: originally inherited as |3.5.11|
```

**Comment by faho** [comment]
@krobelus: This seems suspect:

https://github.com/fish-shell/fish-shell/blob/1e069b0fff20b153bc7f824f9f9b820ca4117e1e/src/input_common.rs#L491

What's that `"\x1b[>5u"` doing there?

**Comment by krobelus** [comment]
ok I'll fix it tomorrow. The `>5u` worked for older iTerm versions (while `=5u` only worked for some of the later ones),
but somewhere around iTerm 3.5.9+ both were broken.
I didn't notice because I was only testing master, not the integration branch..

**Comment by faho** [comment]
Lemme just create an Integration_4.0.1 branch and remove that.

**Comment by faho** [comment]
https://github.com/fish-shell/fish-shell/commit/303af078f38a68b49dfaeeaa513678d8059baa27

**Comment by faho** [comment]
Note: You'll have to remove that entry from $fish_features and restart fish. If you never interacted with that variable before:

```fish
set -e fish_features
```

**Comment by mathbunnyru** [comment]
> Note: You'll have to remove that entry from $fish_features and restart fish. If you never interacted with that variable before:
> 
> set -e fish_features

Yes, I checked that the version built from the branched worked properly without having `fish_features` set.

**Comment by krobelus** [comment]
This fix does the opposite for me.
Same iTerm version (3.5.11), with no `~/Library/Preferences/com.googlecode.iterm2*.plist`

I used `cargo b && target/debug/fish_key_reader -V` and pressed `alt-left`.
On 303af078f3 (Actually disable CSI u in iTerm < 3.5.12, 2025-02-28), I get `\e\[1\;9D` which is `left` (since we don't know this modifier).
If I revert that commit I get `\e\[1\;3D`, `alt-left`.

Unless we find out more, the only way to make both (my and your iterm) work would be to
re-add the iTerm2-labelled bindings removed in c0bcd817ba (Remove obsolete bindings, 2024-04-28).
We probably want to do that for the integration branch.
For master, I need some more time to figure out what's going on (I think 9D means super+left which we want to bind to token movement)

**Comment by krobelus** [comment]
can you post what `fish_key_reader -V` says. Maybe it depends on config

**Comment by krobelus** [comment]
ah the fix is definitely valid for some configurations, we also hit it in https://github.com/fish-shell/fish-shell/issues/11004#issuecomment-2571494782

will add the fallbacks for now, also in master, (reducing differences reduces confusion)

**Comment by krobelus** [comment]
this is what I'll apply to both branches (will wait for a few days in case we find new information)

```patch
Date: Sat, 1 Mar 2025 16:27:59 +0100
Subject: [PATCH] Add back bind aliases to try to address regressions in iTerm2
 3.5.{9,10,11}

Looks like the alt-left breakage was not (or only?) due to us enabling the
kitty keyboard protocol for iTerm2 < 3.5.12.

It seems to also trigger when we don't send any kitty keyboard protocol
enabling sequences.

Unfortunately there are certain scenarios where iTerm2 3.5.11 seems to be
sending the wrong modifier key ("\e[1;9D"). Let's add back those legacy
bindings removed in c0bcd817ba (Remove obsolete bindings, 2024-04-28) and
plan to remove them in a few years.

Note that fish_key_reader still reports this as "left", which already has
a different binding, but it looks like literal matches of legacy sequences
have precedence.

Fixes the problem described in
https://github.com/fish-shell/fish-shell/issues/11192#issuecomment-2692247060

I have no strong opinion on what iTerm2 version should be the first one
we use kitty keyboard protocol with. It needs to be at least 3.5.6 (see
7cfc6297bc (Hack to make alt-{left,right} work again in iTerm2, 2024-08-06)).
But since we're not in a rush and testing all the combinations/regressions
might be a lot of work, let's keep it at 3.5.12.
---
 share/functions/__fish_shared_key_bindings.fish | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/share/functions/__fish_shared_key_bindings.fish b/share/functions/__fish_shared_key_bindings.fish
index 448b644417..9b8a3410a4 100644
--- a/share/functions/__fish_shared_key_bindings.fish
+++ b/share/functions/__fish_shared_key_bindings.fish
@@ -56,9 +56,13 @@ function __fish_shared_key_bindings -d "Bindings shared between emacs and vi mod
 
     bind --preset $argv alt-right nextd-or-forward-word
     bind --preset $argv alt-left prevd-or-backward-word
+    $legacy_bind --preset $argv \e\[1\;9C nextd-or-forward-word # iTerm2 < 3.5.12
+    $legacy_bind --preset $argv \e\[1\;9D prevd-or-backward-word # iTerm2 < 3.5.12
 
     bind --preset $argv alt-up history-token-search-backward
     bind --preset $argv alt-down history-token-search-forward
+    $legacy_bind --preset $argv \e\[1\;9A history-token-search-backward # iTerm2 < 3.5.12
+    $legacy_bind --preset $argv \e\[1\;9B history-token-search-forward # iTerm2 < 3.5.12
     # Bash compatibility
     # https://github.com/fish-shell/fish-shell/issues/89
     bind --preset $argv alt-. history-token-search-backward
-- 
2.48.1
```

**Comment by mathbunnyru** [comment]
> can you post what `fish_key_reader -V` says. Maybe it depends on config

I removed the config files `rm -rf .config/fish/` (for now I was using hotfix mentioned above); then opened a new tab, the issue became present again.

Then pressed alt+right in fish_key_reader 

```
fish_key_reader -V
Press a key:
# decoded from: \e\[C
bind right 'do something
```

**Comment by krobelus** [comment]
> Then pressed alt+right in fish_key_reader 
> 
> ```
> fish_key_reader -V
> Press a key:
> # decoded from: \e\[C
> bind right 'do something

Are you absolutely sure your fish did not print `"\x1b[>5u"`?
You can confirm by running it inside `script`.

In case it makes a difference, try with an empty iTerm2 config (as
described above)

**Comment by krobelus** [comment]
> for now I was using hotfix mentioned above); then opened a new tab, the issue became present again

sounds like your new tab executed the wrong fish binary, since it's sending `\e\[C`
As you mentioned above, the fix we merged has worked for you; I don't see why it would stop working.

**Comment by mathbunnyru** [comment]
> > for now I was using hotfix mentioned above); then opened a new tab, the issue became present again
> 
> sounds like your new tab executed the wrong fish binary, since it's sending `\e\[C` As you mentioned above, the fix we merged has worked for you; I don't see why it would stop working.

I think you missed this part of my message:

> I removed the config files `rm -rf .config/fish/`

`set -Ua fish_features no-keyboard-protocols` wrote a line there so it was expected that fix stopped working.

If you want me to test something please tell me:

1. If I should test with hot fix enabled
2. If I should test with my iTerm2 config or should I reset the config
3. What exactly should I run

**Comment by krobelus** [comment]
Please test with your iTerm config

    for commit in 303af07~ 303af07
        git checkout $commit && cargo b && fish_features= target/debug/fish_key_reader -V
    end

and after both "Press a key" prompts, press `alt-right` and report the `fish_key_reader` output.

---

On an empty iTerm config, I get `\e\[1\;3C` on the first commit and `\e\[1\;9C` on the second commit (303af07).

If any shows `# decoded from: \e\[C`, that would be a very interesting find.

**Comment by mathbunnyru** [comment]
> Please test, with your iTerm config,
> 
> ```
> for commit in 303af07~ 303af07
>     git checkout $commit && cargo b && fish_features= target/debug/fish_key_reader -V
> end
> ```
> 
> and after both "Press a key" prompts, press `alt-right` and report the `fish_key_reader` output.
> 
> On an empty iTerm config, I get `\e\[1\;3C` on the first commit and `\e\[1\;9C` on the second commit ([303af07](https://github.com/fish-shell/fish-shell/commit/303af078f38a68b49dfaeeaa513678d8059baa27)).
> 
> If any shows `# decoded from: \e\[C`, that would be a very interesting find.

```
HEAD is now at 1e069b0ff Cargo metadata: bump version number
   Compiling fish v4.0.0 (/Users/asalikhov/Documents/oss/fish-shell)
   Compiling fish-printf v0.2.1 (/Users/asalikhov/Documents/oss/fish-shell/printf)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.10s
Press a key:
# decoded from: \e\[C
bind right 'do something'
Previous HEAD position was 1e069b0ff Cargo metadata: bump version number
HEAD is now at 303af078f Actually disable CSI u in iTerm < 3.5.12
   Compiling fish v4.0.0 (/Users/asalikhov/Documents/oss/fish-shell)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.92s
Press a key:
# decoded from: \e\[1\;3C
bind alt-right 'do something'
```

**Comment by brynjsmith** [comment]
I don't think this is an iTerm2 problem, I've tried it in the default Terminal utility on MacOS, and it does the same thing.

**Comment by mathbunnyru** [comment]
> I don't think this is an iTerm2 problem, I've tried it in the default Terminal utility on MacOS, and it does the same thing.

I didn't have the problem in the default Terminal.

**Comment by krobelus** [comment]
> I've tried it in the default Terminal utility on MacOS, and it does the same thing.

weird. What's the output when typing the affected key into `fish_key_reader -V`?

**Comment by brynjsmith** [comment]
> > I've tried it in the default Terminal utility on MacOS, and it does the same thing.
> 
> weird. What's the output when typing the affected key into `fish_key_reader -V`?
It yells silently in markup, but also this:

From cmd-right-arrow, which is supposed to select just the next element:
`[I] bryn@Bryns-MacBook-Pro ~/.c/f/functions> fish_key_reader -V
Press a key:
# decoded from: \ef
bind alt-f 'do something'`

and from cmd-up-arrow, which is $! in bash:
`[I] bryn@Bryns-MacBook-Pro ~/.c/f/functions> fish_key_reader -V
Press a key:
# decoded from: \e\[A
bind up 'do something'

**Comment by krobelus** [comment]
> From cmd-right-arrow, which is supposed to select just the next element:

This issue was only about the *option* modifier, not *command*.

- *command + right-arrow* rings the terminal bell
- *command + up-arrow* moves to the previous prompt

> `[I] ***@***.*** ~/.c/f/functions> fish_key_reader -V
> Press a key:
> # decoded from: \ef
> bind alt-f 'do something'`

this is what *option-right* does in Terminal.app (legacy reasons)

> and from cmd-up-arrow, which is $! in bash:
> `[I] ***@***.*** ~/.c/f/functions> fish_key_reader -V
> Press a key:
> # decoded from: \e\[A
> bind up 'do something'

can't reproduce this

**Comment by brynjsmith** [comment]
I was not awake yet, I guess, I meant option, I swear, not command.
