### ISSUE TITLE
ERROR: unsafe header/library path used in cross-compilation: '-L' '/usr/local/lib'

### ISSUE THREAD

**Issue by alexs-sh** [fish-shell/fish-shell#11683]
I tried to add **fish** as [Buildroot](https://buildroot.org/) package to make the shell available for embedded devices. During compilation, I encountered an error caused by hardcoded paths to libraries. The error looks like:

<img width="1923" height="371" alt="Image" src="https://github.com/user-attachments/assets/44b91de2-ca1b-4e7c-a174-5db99999dbf6" /> 

See failed CI step [here](https://gitlab.com/alexs-sh/fish-buildroot/-/jobs/10812073171).

The problem comes from the [build.rs](https://github.com/fish-shell/fish-shell/blob/07ff4e7df065e97a008b1b2995169bd61219662e/build.rs#L77). Removing this code allows me to compile fish and run it on target devices. 

<img width="775" height="227" alt="Image" src="https://github.com/user-attachments/assets/bc225088-6634-402b-872e-37ccabd1302b" />

Furthermore, a closer look at the build flags showed that we have some correct -L flags (they are aware that we're doing cross-compilation and point to the correct paths), while ```-L /usr/local/lib``` points to a system directory that contains files for a different architecture. Using this path is incorrect.
 
```
...
"-L" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-4.0.2/target/aarch64-unknown-linux-gnu/release/build/fish-38e74c2167bab091/out" \
"-L" "/usr/local/lib" \
"-L" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-4.0.2/target/aarch64-unknown-linux-gnu/release/build/pcre2-sys-223868596835ddbe/out"
...
```

Since the Rust subsystem in Buildroot is still quite new, it's not entirely clear what exactly needs to be changed, and I’d like to discuss this. On one hand, hardcoded flags seem like the wrong approach; on the other hand, I might have forgotten or missed something on the Buildroot side, and it ends up jumping into an unexpected build flow.

Buildroot info:
 - [mk-file](https://gitlab.com/alexs-sh/buildroot/-/blob/try-fish-shell/package/fish/fish.mk?ref_type=heads) -  contains all necessary info: fish versions, build flags, commands which Buildroot should run to build the package
 - [config](https://gitlab.com/alexs-sh/fish-buildroot/-/blob/master/configs/qemu_aarch64_virt_defconfig?ref_type=heads) - contains information about the environment such as compiler, kernel, libc, ...
 - [patch](https://gitlab.com/alexs-sh/buildroot/-/blob/try-fish-shell/package/fish/0001-build.rs-remove-hardcoded-usr-local-lib.patch?ref_type=heads) with workaround -  removes hardocded values and allows to have buildable / runnable fish

Fish version: 4.0.2
Build host: Debian 12, ArchLinux

If you need any additional details, checks, or tests, please let me know.

Thank you!

**Comment by alexs-sh** [comment]
Some more observations. 
- The hardcoded paths were added here: https://github.com/fish-shell/fish-shell/commit/b17124d8d23fc9c438b49f5b78593d4fb93278fb 
- I removed them in my [forked](https://github.com/alexs-sh/fish-shell) repo. Seems CI is happy with that. But of course, this is just for experimentation and for better understanding the history and reasoning behind the flags. It seems that fish doesn't require them, but they might still be necessary when building packages for distros or for building from source that expect to use /usr/local.

**Comment by alexs-sh** [comment]
@mqudsi Hello Mahmoud,

I hope you don’t mind me reaching out to you directly. I noticed you were the author of the changes, and I thought you might be able to shed some light on the history, reasoning, and possible fixes for the issue.

Thank you in advance

**Comment by krobelus** [comment]
Maybe this was added to allow discovering the gettext library (`libintl.so`?) in the default install location `/usr/local/lib`.
This is probably not quite kosher, I don't think other projects do the same.
So if we can confirm that users can make fish link against `/usr/local/lib/libintl.so` by setting standard environment variables supported by `cc-rs`, such as `CFLAGS="-I/usr/local/include -L/usr/local/lib"` then we should be good to remove it.

**Comment by alexs-sh** [comment]
Yep. Based on my experience, projects often follow one of two common approaches:

- Rely on finding dependencies during configuration using CMake commands like find_library, or using pkg-config, or similar tools.

- Rely on user-provided configuration through -I/-L flags or custom prefix paths.

Hardcoded paths are rare and usually used when the internal structure of a library or module is well known. Unfortunately, they almost always break something during migration or porting.

"So if we can confirm that users can make fish link against " -  I can try to do that, but I’m afraid I might run into the “it works on my machine” problem. Maybe you know some specific steps or cases to test, or perhaps I should try applying the changes on Debian, Arch, ..., packages?

**Comment by zanchey** [comment]
Dropping this breaks gettext on both cargo and CMake builds on FreeBSD. The gettext library path needs to passed from CMake to build.rs. Translations don't work in cargo builds at the moment anyway.

**Comment by alexs-sh** [comment]
Hmmm... that's interesting. I can build @zanchey [changes](https://github.com/zanchey/fish-shell/commit/debc66d0aaa82139b280a087714bf1d0d9f23db0) on FreeBSD.  Both CMake and Cargo are working well. 

To test CMake I followed the build steps from README:

```
mkdir build; cd build
cmake ..
cmake --build .
```

The ```WITH_GETTEXT``` flag is ```ON```. I can see that gettext has been found. 

Using ``make`` instead of `cmake --build` also worked well. And it seemed to produce even more detailed output.


```
-- Setting build type to default 'RelWithDebInfo'
-- Trying to use PCRE2 from the system
-- The following features have been enabled:

 * gettext, translate messages with gettext

-- The following OPTIONAL packages have been found:

 * Gettext

-- The following REQUIRED packages have been found:

 * Rust

-- The following features have been disabled:

 * Documentation, user manual and documentation

-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/user/projects/fish-shell-zanchey/build
...

   Compiling fish v4.1.0-alpha0 (/home/user/projects/fish-shell-zanchey)
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
2.1.0-17645-gdebc66d0a
[ 90%] Built target CHECK-FISH-BUILD-VERSION-FILE
[100%] Generating fish.pc
[100%] Built target build_fish_pc
    Finished `release-with-debug` profile [optimized + debuginfo] target(s) in 1m 08s
   Compiling fish v4.1.0-alpha0 (/home/user/projects/fish-shell-zanchey)
[100%] Built target fish
    Finished `release-with-debug` profile [optimized + debuginfo] target(s) in 1m 52s
   Compiling fish v4.1.0-alpha0 (/home/user/projects/fish-shell-zanchey)
[100%] Built target fish_indent
    Finished `release-with-debug` profile [optimized + debuginfo] target(s) in 2m 05s
[100%] Built target fish_key_reader
```

FreeBSD info:

```
user@freebsd-fish:~/projects/fish-shell-zanchey/build $ cat /etc/os-release
NAME=FreeBSD
VERSION="14.3-RELEASE"
VERSION_ID="14.3"
```

The ```libgettext*``` and ```libintl*``` libraries are located in ```/usr/local/lib```. I installed everything using pkg. No manual builds.


I also tried building with a different ```CMAKE_INSTALL_PREFIX ``` (e.g. /tmp), and it worked well for me too.

**Comment by zanchey** [comment]
CMake finds gettext, but it's not linked in to the actual binary, and it doesn't work:

```
> cmake .
-- Trying to use PCRE2 from the system
-- The following features have been enabled:

 * gettext, translate messages with gettext

-- The following OPTIONAL packages have been found:

 * Gettext
[snip]
> LANG=de_DE.UTF-8 /usr/local/bin/fish -c '_ file'; echo
Datei
> LANG=de_DE.UTF-8 ./fish -c '_ file'; echo
file
> ldd ./fish
./fish:
        libthr.so.3 => /lib/libthr.so.3 (0x180ad5fb4000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x180ad4cdb000)
        libc.so.7 => /lib/libc.so.7 (0x180ad6437000)
        libm.so.5 => /lib/libm.so.5 (0x180ad544a000)
        [vdso] (0x7ffffffff000)
```

**Comment by alexs-sh** [comment]
Thank you for the clarification

**Comment by mqudsi** [comment]
If I remember correctly (this *was* some time ago), I believe this was a mix of experimentation and reverse engineering what the existing C++ build system did underneath the hood, but with the caveat that we don't (yet?) use pkg-config in the rust build stage.

(Also, pkg-config isn't *as* used on FreeBSD as it is on other platforms)

**Comment by alexs-sh** [comment]
Some more observations.

**1. Linux and fish v4.0.2:**
    gettext and locales work correctly with the CMake build. They do not depend on hardcoded paths in build.rs.
    For example:
```
LANG=pl_PL.UTF-8 ./build/fish -c 'x=100'
fish: Nieobsługiwane użycie '='. W fish używane jest 'set x 100'.
x=100
^~~~^
```
This works as expected.

**2. Linux and fish master:**
Locales do not work, with or without hardcoded paths. The build environment and commands are the same as for v4.0.2 build

    LANG=pl_PL.UTF-8 ./build/fish -c 'x=100'
    fish: Unsupported use of '='. In fish, please use 'set x 100'.
    x=100
    ^~~~^

**3. FreeBSD and fish v4.0.2:**
    Locales work only with hardcoded paths in build.rs

**4. FreeBSD and fish master:**
    Locales do not work, regardless of hardcoded paths. The same as for Linux and fish master


Could you please try to reproduce this on your side? Is the issue repeatable? If so, it seems that removing the hardcoded paths is only a secondary reason for the broken translations .

**Comment by zanchey** [comment]
Yeah, looks like it was broken by bf65b9e3a74028533 from #11195

**Comment by krobelus** [comment]
> Yeah, looks like it was broken by bf65b9e3a74028533 from #11195 

yikes. That commit should have never been merged.  It changed too
many things at once (there were at least 4 problems, see "git log
--grep=bf65b").

**Comment by krobelus** [comment]
Nevermind actually; the reason why it kinda worked before that commit
was that we used to use LOCALEDIR (/usr/local/share/locale) even when
run from the build directory.
This was weird. Now we use "./share/locale" (see "fish -d config"),
which is less weird.

"share/locale" is currently only populated if you run
"build_tools/update_translations.fish".

This is not ideal but probably something we can ignore?
("build/fish" has other issues as well IIRC)
Something like https://github.com/fish-shell/fish-shell/pull/11726 might improve things.

**Comment by zanchey** [comment]
Nah, it's using `share/fish/locale`, which is wrong:

https://github.com/fish-shell/fish-shell/commit/bf65b9e3a74028533fdeb557294c6aadc3d63db9#diff-431d873b0fde9147e8c72c8691c3f0aff92c8b0c2d355eb88aafbf4769349b17R97

**Comment by krobelus** [comment]
yeah it wrongly used `share/fish/locale` when run from an installation (i.e. not from the source tree),
but that has been fixed in c3740b85be4 (config_paths: fix compiled-in locale dir, 2025-06-12)

**Comment by alexs-sh** [comment]
I’m not sure I fully understand what was fixed 😄  (it seems there were several mixed issues) 

Anyway, in the latest version (67e86571097e6ac35a637344064aa6445f07da03 from Aug 23), I still see the same issue during cross-compilation. And the same hardcoded [paths](https://github.com/fish-shell/fish-shell/blob/67e86571097e6ac35a637344064aa6445f07da03/build.rs#L56) in build.rs which lead to mixing headers/libraries for different architectures.

```
  Compiling pcre2 v0.2.9 (https://github.com/fish-shell/rust-pcre2?tag=0.2.9-utf32#85b7afba)
error: linking with `arm-none-linux-gnueabihf-gcc` failed: exit status: 1
  |
  = note:  "arm-none-linux-gnueabihf-gcc" "/tmp/rustcYXpQNw/symbols.o" "<4 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-67e86571097e6ac35a637344064aa6445f07da03/target/armv7-unknown-linux-gnueabihf/release/deps/{libfish-5b3aeaa7b18c2ece.rlib,libterminfo-88510fdf93860da5.rlib,libphf-3cdab2b3fd60d5de.rlib,libphf_shared-d52909238fa2e06b.rlib,libsiphasher-b7abdab0a7f6b222.rlib,libfnv-f6a8c7cdb6331796.rlib,libnom-34f3f88c41e6b835.rlib,libmemchr-a17bc937ed2a407e.rlib,libnix-3c85bccd8502a67f.rlib,librand-a43b2ff30c1449f9.rlib,librand_core-54f0e30d4458e580.rlib,libfish_printf-afb9cf777b8c35b9.rlib,libunicode_width-1dd476885c428e5e.rlib,libunicode_segmentation-c0b764a7d72d0295.rlib,libwidestring-9c2d58e403b4ce93.rlib,librust_embed-9fa2b0ef5b4dcd5d.rlib,librust_embed_utils-0d55dfe48fa5d1a5.rlib,libwalkdir-78c1fecaac41dba4.rlib,libsame_file-14732a60894ccc82.rlib,libsha2-a5314d993a50b77a.rlib,libcfg_if-82bc207afde4f794.rlib,libdigest-ab0b38d54daa2fd2.rlib,libblock_buffer-2877a0fc45484559.rlib,libcrypto_common-7fbbe907c266a28f.rlib,libgeneric_array-1b64409f6766382d.rlib,libtypenum-69a29b86e03d7888.rlib,liblru-4fa06ba0b2f3a1df.rlib,libhashbrown-06fa2c9ad981db52.rlib,libfoldhash-d97844f9a2fc8c42.rlib,libequivalent-40f4c07c62f9c263.rlib,liballocator_api2-b45823af81411ab4.rlib,libpcre2-47d27530d7f0df72.rlib,liblog-9f2a1bf257270892.rlib,libpcre2_sys-0b9a536da73c6f37.rlib,libnum_traits-532cc8e71cbed438.rlib,liberrno-761cc82406bb205a.rlib,libonce_cell-486448fd66fec79f.rlib,liblibc-9b9a5dd6ffbe16d0.rlib,libbitflags-edd1b8923b60f644.rlib}.rlib" "<sysroot>/lib64/rustlib/armv7-unknown-linux-gnueabihf/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,libcfg_if-*,liblibc-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-67e86571097e6ac35a637344064aa6445f07da03/target/armv7-unknown-linux-gnueabihf/release/build/fish-7c3639ea6ae1441b/out" "-L" "/usr/local/lib" "-L" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-67e86571097e6ac35a637344064aa6445f07da03/target/armv7-unknown-linux-gnueabihf/release/build/pcre2-sys-edaff49bb64b3b25/out" "-L" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-67e86571097e6ac35a637344064aa6445f07da03/target/armv7-unknown-linux-gnueabihf/release/build/pcre2-sys-edaff49bb64b3b25/out" "-L" "<sysroot>/lib64/rustlib/armv7-unknown-linux-gnueabihf/lib" "-o" "/builds/alexs-sh/fish-buildroot/buildroot/output/build/fish-67e86571097e6ac35a637344064aa6445f07da03/target/armv7-unknown-linux-gnueabihf/release/deps/fish_indent-46fdb26d40046725" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-debug" "-nodefaultlibs" "-Wl,--allow-multiple-definition"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: arm-none-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-L' '/usr/local/lib'
```

Failed CI step is [here](https://gitlab.com/alexs-sh/fish-buildroot/-/jobs/11116288378)

**Comment by zanchey** [comment]
Yeah, translation paths are still broken in e96300b08 when installed:

```
openat(AT_FDCWD, "/home/wheel/zanchey/prefix/share/fish/locale/de/LC_MESSAGES/fish.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```

(actual files are in `/home/wheel/zanchey/prefix/share/locale/de/LC_MESSAGES/`)

Probably all this will be obviated by #11726 though

**Comment by krobelus** [comment]
> Yeah, translation paths are still broken in e96300b08 when installed:
> 
> ```
> openat(AT_FDCWD, "/home/wheel/zanchey/prefix/share/fish/locale/de/LC_MESSAGES/fish.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
> ```
> 
> (actual files are in `/home/wheel/zanchey/prefix/share/locale/de/LC_MESSAGES/`)

right, fixed by 21a07f08a36 (config_paths: fix compiled-in locale
dir for installed, non-embed builds, 2025-08-25).

> 
> Probably all this will be obviated by #11726 though

yeah.
The "-L/usr/local/lib" thing too.
It'd probably also be fine to make us add "-L/usr/local/lib" only on BSD..
but probably no need, #11726 should make it in fairly soon
