### ISSUE TITLE
`fish -n` reports error on valid fish.config containing `alias`.

### ISSUE THREAD

**Issue by weakish** [fish-shell/fish-shell#1788]
How to reproduce ?

``` fish
; echo 'alias puts=echo' > fish.config                                                                                                        
; fish -n fish.config                                                                                                                        
fish: The file '.' is not executable by this user
/tmp/fish.config (line 1): . /usr/share/fish/functions/alias.fish
                           ^
in command substitution
        called on line 1 of file “/tmp/fish.config”,

/tmp/fish.config (line 1): alias puts=echo
```

When fish starts up and loads fish.config, it will not complain about  `alias` in it, though.

**Comment by krader1961** [comment]
Sometime since this was opened it has been fixed; possibly inadvertently while fixing something else.

**Comment by zanchey** [comment]
`echo . | fish -n` still fails for me.

I don't remember why `.` is defined in `config.fish` instead of a `..fish` file.

**Comment by krader1961** [comment]
The reason I couldn't reproduce this on 5/22 and closed the issue is that I was using the steps in the original problem statement. That no longer fails because the `abbr` command no longer uses `.`. In fact, I can't find any standard fish function that uses `.` rather than `source`.

The current definition is from commit 5818289c2 in response to issue #310. Sadly neither the issue or commit message makes clear why the function is defined in the global *config.fish*.

In any event I think this is a non-issue now that fish uses `source` everywhere. There is absolutely no need for `fish -n` to support the long since deprecated `.` synonym for `source`.
