### ISSUE TITLE
Rsync does not tab complete directories with spaces

### ISSUE THREAD

**Issue by benoliver999** [fish-shell/fish-shell#1872]
`rsync -rP remote:directory<tab>` removes the directory altogether and ends up as `rsync remote:`

Manually entering the file name works fine, as does using a wildcard. The completion works as expected in bash.

scp also works fine with the tab completion.

**Comment by zanchey** [comment]
This is because of the awk pipeline using `$NF` instead of printing all fields beyond 5. Unfortunately the required text transformation ("add a / on the end if the line starts with d and then drop the first four fields") is impressively difficult with any of the standard text tools.

**Comment by zanchey** [comment]
Fixed - thanks!

**Comment by ocharles** [comment]
That doesn't seem to fix it - the tab completion only escapes it on the client side - you need to double escape for `rsync`. That is to say using the tab completion doesn't actually refer to the correct file.

**Comment by zanchey** [comment]
This looks like the perfect candidate for conversion to the built-in string utility - piping through `string escape -n` a couple times should help.

**Comment by faho** [comment]
@zanchey: I've got a fix for this, but it's not looking great:

```fish
#
# Hostname completion
#
complete -c rsync -d Hostname -a "

(__fish_print_hostnames):

(
	#Prepend any username specified in the completion to the hostname
	commandline -ct |sed -ne 's/\(.*@\).*/\1/p'
)(__fish_print_hostnames):

(__fish_print_users)@\tUsername

"

#
# Remote path
#
complete -c rsync -d "Remote path" -n "commandline -ct | string match '*:*'" -a "
(
	#Prepend any user@host:/path information supplied before the remote completion
	commandline -ct | string replace -r '/[^/]*\$' '/'
)(
	#Get the list of remote files from the specified rsync server
    # The string match ensures we only complete remote paths (rsync will error out if given nothing, and stderr is ignored)
    # The string replace removes everything up to and including a time (since rsync will justify its output)
    # The grep -v removes the "." line referring to the directory
    #TODO: Replace the `grep` call with `string`
	rsync --list-only ^/dev/null (commandline -ct | string match -r '.*:(.*/)?') | string replace -r '.*[0-9]{2}:[0-9]{2}:[0-9]{2} ' '' | grep -v '^.\$' | string escape -n
)
"
```

The `grep -v` really irks me and I've replaced the regexes with simpler ones - I don't like using regexes I don't understand - so there might be edgecases I don't see.

**Comment by nh2** [comment]
Confirming this bug. When I have a target dir `my\ dir` on the remote side, and start with `scp` or `rsync myfile otherhost:my` and press TAB, then:

* `zsh` completes correctly to `otherhost:my\\\ dir/`
* `fish` completes incorrectly to `otherhost:my\ dir/`

and consequently fish copies everything into a new dir called `my`.

**Comment by faho** [comment]
@nh2: Can you try my fix (needs fish from git though)?

**Comment by nh2** [comment]
@faho how recent git do I need and where does your code go?

**Comment by faho** [comment]
@nh2: You'll need #2296, so any build from the last couple of months should do, and my code goes into ~/.config/fish/completions/rsync.fish. Best make a copy of the other rsync.fish (in one of the directories $fish_complete_path) there and put the code into the right place.

**Comment by devster31** [comment]
@faho I'm using `fish, version 2.7.0` on MacOS but I'm still seeing this issue.

**Comment by faho** [comment]
@devster31: We've never merged the fix, since I couldn't test it. Would you mind checking [my fix](https://github.com/fish-shell/fish-shell/issues/1872#issuecomment-162012407)? You'd have to

- Copy the rsync completion script to ~/.config/fish/completions (from its other place in $fish_complete_path)

- Modify the "Remote path" part at the end to match what I did

**Comment by devster31** [comment]
I just tried your snippet, the path is correctly escaped, there's a difference vs zsh however.
ZSH:
```
host.com:data/my\\\ long\\\ folder/
```
Fish:
```
host.com:data/my\\\ long\\\ folder█
```
The big black rectangle is only to show that there's a whitespace there at the end despite the directory being a folder.

**Comment by faho** [comment]
>The big black rectangle is only to show that there's a whitespace there at the end despite the directory being a folder.

That's because fish thinks the token is complete. I'll have to look up how we do it in other completions.

In the meantime, can you try replacing that space with a "/" and pressing tab again?

**Comment by devster31** [comment]
Adding a slash doesn't list anymore files, and starting the name doesn't list it either.
ZSH:
```
host.com:data/my\\\ long\\\ folder/my [press TAB]
host.com:data/my\\\ long\\\ folder/my\\\ file
```
Fish:
```
host.com:data/my\\\ long\\\ folder/ [press TAB -> nothing]
host.com:data/my\\\ long\\\ folder/my [press TAB -> nothing]
```

**Comment by faho** [comment]
@devster31: What does `rsync --list-only host.com:data/my\\\ long\\\ folder/my` print?

**Comment by devster31** [comment]
```
rsync --list-only host.com:data/my\\\ folder
drwxrwxr-x          4,096 2018/01/07 03:19:51 my folder

rsync --list-only host.com:data/my\\\ folder/
drwxrwxr-x          4,096 2018/01/07 03:19:51 .
-rw-rw-r--              0 2018/01/07 03:19:51 my file

rsync --list-only host.com:data/my\\\ folder/my
rsync: link_stat "/home/user/my folder/my" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1721) [Receiver=3.1.2]
rsync: [Receiver] write error: Broken pipe (32)

rsync --list-only host.com:data/my\\\ folder/my\*
-rw-rw-r--              0 2018/01/07 03:19:51 my file
```

**Comment by 2m** [comment]
I have also been bitten by this recently. Anything I could do to help out?

**Comment by devster31** [comment]
The latest workaround seem to add an extra space at the end of a directory.
Furthermore it seems it stops autocompleting deeper paths after that, so for example:
```
rsync user@host.com:/my/path/with\\\ spaces # gets a trailing space here
rsync user@host.com:/my/path/with\\\ spaces/file with spaces # completion does not work for this path
```

I'm running `fish version 3.0.2 on Darwin`
