### ISSUE TITLE
fish_config outputs (lots of) favicon.ico 403 errors

### ISSUE THREAD

**Issue by Moter8** [fish-shell/fish-shell#1936]
```
carstenh@arch-moteer8 ~> fish -v
fish, version 2.1.1-1126-g9a34df6
Chromium Version 39.0.2171.95 (64-bit)
```
```
carstenh@arch-moteer8 ~> fish_config 
Web config started at 'file:///home/carstenh/.cache/fish/web_config-FD7Y1Y.html'. Hit enter to stop.
Created new window in existing browser session.
::1 - - [03/Feb/2015 16:32:28] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:31] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:32] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:32] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:32] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:33] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:33] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:34] code 403, message Forbidden, path /favicon.ico
::1 - - [03/Feb/2015 16:32:35] code 403, message Forbidden, path /favicon.ico

```
Each error corresponds to one F5/refresh of the page
Screenshot: http://i.imgur.com/KhwLVFE.png

**Comment by NathanJang** [comment]
@ridiculousfish What do you think about this?
![fish-favicon](https://cloud.githubusercontent.com/assets/7534708/7415572/74a45854-ef8c-11e4-8885-3a7c09a7fb75.png)

Just took the webpage's background colour and the Courier `f` from "fish". It'd be trivial to add this to the website's HTML, if I'm not wrong.

**Comment by faho** [comment]
This should be fixed in #2048. As always please mention if it isn't.

**Comment by frederickjh** [comment]
A quick question, I am using fish version 2.2.0 on Ubuntu 14.04.4 and I am still seeing these favicon.ico 403 error messages. Should this be fixed in this version of fish?

After looking at fish-shell/fish-shell#2048, I looked in /usr/share/fish/tools/web_config/ but there is no favicon.ico in that folder. There is only one image file called delete.png

**Comment by frederickjh** [comment]
Copying the **favicon.png** to `/usr/share/fish/tools/web_config/favicon.png` and then adding a **`<link rel>`** tag after the **`<meta>`** tag like this in the index.html in the same folder stopped the favicon.ico 403 errors.
```
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
    <link rel="icon" href="favicon.png" type="image/png" />
```
