### ISSUE TITLE
Tab completions failed

### ISSUE THREAD

**Issue by Mabinogiysk** [fish-shell/fish-shell#2099]
I installed fish shell on a super computer, the tab completions can not work on the directory ~/, niether path nor scripts in this directory(I have added it into $PATH and all of it works well in bash shell). But I can use the command or path in full name.

**Comment by zanchey** [comment]
Can you show us exactly what is happening, and what you expect? I added `~` to my `$PATH` and tab-completion for programs in that directory works fine, behaving exactly like bash in my testing.

**Comment by Mabinogiysk** [comment]
I suppose this because the special operation system of the super computer tianhe-2， you can find more information on wiki. The tab completions can't work only when I try to get access to the directory and scripts in ~/, and when I am in ~/, directory path can be completed, but command completions still can't work. I can send pictures of this error if you can leave a email.

**Comment by ridiculousfish** [comment]
fish is running on tianhe-2? :astonished:

**Comment by zanchey** [comment]
Wow!

You certainly can email us - zanchey@ucc.gu.uwa.edu.au works (my key is on keybase.io/zanchey if you need it).

**Comment by Mabinogiysk** [comment]
not exactly, fish only runs on login nodes on tianhe-2

**Comment by zanchey** [comment]
@Mabinogiysk has kindly sent some screenshots which demonstrate the behaviour described: tab-completions for the commands in `~/bin` don't work unless the current working directory is `~/bin`.

I wonder what fish does that is different to bash, and whether there might be something unusual about the underlying filesystem on tianhe-2? A quick `strace` on my system shows nothing obvious.

**Comment by ridiculousfish** [comment]
I got the images but they came a little mixed up, all at the bottom of the email. @zanchey can you please try re-sending them to me again with the images inline?

I wonder if `$HOME` has the wrong value, or is a funny symlink? The value in `$PATH` is a literal path (no tilde) so it won't be affected by `$HOME`. Maybe we're mishandling that.

**Comment by ayurmedia** [comment]
I have similar problems, works in osx, but fails in linux (gentoo). it does not expand ~/ and does not autocomplete it. i don't have access to /usr/local, so i installed fish in ~/bin/fish . installed fish from source.

**Comment by ridiculousfish** [comment]
What do you mean by "does not expand ~/?"

**Comment by ayurmedia** [comment]
if i am i fishshell and type 
"cd ~/" then normally in osx it will show me some suggestions. 
if i know some parts and type
"cd ~/ba" for ~/backup then i get some suggestions in grey but if i hit tab-key, then the typed text flashes in dark red background, and nothing happens. in osx, it would now expand the path into
"cd ~/backup" . 

also it seems in osx i have to type "alt+n" and then space for it to get registered correctly. but usually "alt-n" and then "/" also works. (on my keyboard alt-n produces the ~ -key) (macbook).

**Comment by pickfire** [comment]
I am using arch linux but it works. Do you `mv /somefile ~/ba/su` and <**tab**>?

**Comment by ayurmedia** [comment]
@pickfire no i did "mv /somefile ~/ba<tab> , nothing happens, 
press "->" then gets expanded now. 
"mv /somefile ~/backup/su<tab> same as above. 

if i use the full path like "/home/userx/ba<tab>" then it works. 
something special with the ~ expansion.

**Comment by pickfire** [comment]
On Thu, Jun 18, 2015 at 01:25:25AM -0700, ayurmedia wrote:
>@pickfire no i did "mv /somefile ~/ba<tab> , nothing happens,
>press "->" then gets expanded now.
>"mv /somefile ~/backup/su<tab> same as above.
>
>if i use the full path like "/home/userx/ba<tab>" then it works.
>something special with the ~ expansion.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fish-shell/fish-shell/issues/2099#issuecomment-113073991

I can't reproduce your problem. Which version are you using?

-- 
 _____________________________________
< Do what you like, like what you do. >
 -------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by ayurmedia** [comment]
@pickfire fish, version 2.2b1-36-gd018ef3 

server is gentoo linux

**Comment by zanchey** [comment]
If you could run fish under `strace` that might help diagnose the issue, although the output is very large.

If you need help with how to do that, let me know.

**Comment by ayurmedia** [comment]
@zanchey i run it with strace and as i guessed its a problem that parent folder of $HOME is not readable, and fish tries to access it anyways and crashes with the access denied. 

bash manages to to tab-complete so its a bug in the implementation of fish. 

part of the strace: 

rt_sigaction(SIGCHLD, {0x80d7d20, [], SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGWINCH, {0x80d7cf0, [], SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGHUP, {0x80d7dc0, [], SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGTERM, {0x80d7cc0, [], SA_SIGINFO}, NULL, 8) = 0
lstat64("/kunden", {st_mode=S_IFDIR|0751, st_size=4096, ...}) = 0
lstat64("/kunden/134447_80331", {st_mode=S_IFDIR|0710, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 6
lseek(6, 0, SEEK_SET)                   = 0
getdents64(6, /* 27 entries */, 32768)  = 704
stat64("/kunden", {st_mode=S_IFDIR|0751, st_size=4096, ...}) = 0

** HERE IS THE PROBLEM **

openat(AT_FDCWD, "/kunden/", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = -1 EACCES (Permission denied)
getdents64(6, /* 0 entries */, 32768)   = 0
close(6)                                = 0
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
stat64("/kunden/134447_80331/.config/fish/fishd.1c6f65cd6ed4", {st_mode=S_IFREG|0600, st_size=1147, ...}) = 0
write(1, "\10\10\10\10\10\10\10\10\33[1m\33[45mcd ~/web\33(B\33[m\33"..., 94) = 94
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
nanosleep({0, 100000000}, NULL)         = 0
gettimeofday({1434625517, 983702}, NULL) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
clone(child_stack=0xe3507424, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0xe3507ba8, {entry_number:12, base_addr:0xe3507b40, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}, child_tidptr=0xe3507ba8) = 14978
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
select(6, [0 3 5], NULL, NULL, {4294, 967295}) = 1 (in [3], left {4294, 967293})
read(3, "d", 1)                         = 1
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(1, "\10\10\10\10\10\10\10\10\33[38;5;26mcd\33[30m\33(B\33[m "..., 97) = 97
fstat64(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat64(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
select(6, [0 3 5], NULL, NULL, {4294, 967295}) = 1 (in [0], left {4292, 151429})
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
read(0, "\t", 1)                        = 1
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
select(6, [0 3 5], NULL, NULL, {4294, 967295}

**Comment by zanchey** [comment]
Nice work. I can reproduce this with an intermediate unreadable directory:

```sh
mkdir -p /tmp/foo/blah
printf '#!/bin/sh\necho blah\n' > /tmp/foo/blah/blah.sh
chmod 700 /tmp/foo/blah/blah.sh
set -gx PATH /tmp/foo/blah $PATH
blah<TAB> # completes to blah.sh
chmod 100 /tmp/foo
blah<TAB> # fails
```

I think this is because fish only recurses in `wildcard_expand_internal` if the `wreaddir` on each component succeeds.

**Comment by ridiculousfish** [comment]
Fantastic!

**Comment by ridiculousfish** [comment]
The way wildcard expansion works for a path segment is that it enumerates over the directory, using `readdir()` until it finds a match. If we have a literal path segment, we should instead just assume we have a match and try to access it. That ought to be faster as well.

The wildcard expansion code is horrible and this makes it worse - a very good candidate for refactoring!

**Comment by ridiculousfish** [comment]
4621e763b63dd764bc96cc5fe36613b4e0404e6b should fix this. @ayurmedia or anyone else, if you are able to test on master I'd very much appreciate it. Thanks for reporting this!

**Comment by ayurmedia** [comment]
Hi, i can confirm that it now works on my special sandboxed linux version. thanks for the fast fix. 

i still have another unrelated bug, if i open ~/we<tab> it expands to ~/webseiten/ correctly. if i tab again, it lists all subfolders, but instead of ~/webseiten/website1 ~/webseiten/website1 , it will show $webseiten/webseite1 . i have similiar glitches with other folders also. ~/ms_appl/* turns into $/ms_appl. and so on. something is wrong here. its not a big deal, so i am happy with the version now.

**Comment by ridiculousfish** [comment]
The $ appears in the pager (below the prompt), right? I think you're probably seeing the character we use in place of ellipsis when the term doesn't support Unicode. Can you confirm that running `locale` doesn't show UTF-8 support?

Probably we should pick a different ellipsis character than $, it's too confusing.

**Comment by ayurmedia** [comment]
my locale: 

$ locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=


wrong display looks like this:  (in promt ~/ is correct, in the suggest-list its replaced into $)
cd ~/PEAR/PEAR/ < tab >
$EAR/PEAR/ChannelFile/  $EAR/PEAR/Downloader/  $EAR/PEAR/Installer/    $EAR/PEAR/REST/  $EAR/PEAR/Validator/
$EAR/PEAR/Command/      $EAR/PEAR/Frontend/    $EAR/PEAR/PackageFile/  $EAR/PEAR/Task/

**Comment by ridiculousfish** [comment]
Thanks, yep, that's definitely what's going on. I wonder how we should show these completions that are too long.

**Comment by ayurmedia** [comment]
no problem with too long, simply show ~/ instead of $. or do you mean it should look like "...EAR/" ? seems tcsh does not support autocomplete, in bash you get the question (show all y/n). maybe you should not repeat the whole path, but do it like in bash, and only show the subfolder-name, then you also save a lot of space and don't need to shorten it with ellipses. the prompt above shows the beginning of the path, so showing it in the suggest list is not needed.

**Comment by ayurmedia** [comment]
if you choose to use an ellipsis character you could simply use 3 dots (which might use more space in mono-font) i would suggest to us a different color for the ellipsis, so its clear its not a real character but some special case for abbreviation.

**Comment by ridiculousfish** [comment]
I cherry picked a fix for the original issue (wildcard expansion with no read permission in parent directories) to Integration_2.2.0 as ecb2da314214afde1afea6a1c943f26c3e5ada2d. Hopefully this is the last fix in that branch!

**Comment by pickfire** [comment]
> fish is running on tianhe-2? :astonished:

`fish` now have the world king supercomputer.

http://www.zdnet.com/article/chinas-tianhe-2-still-king-supercomputer-but-us-has-more-systems-in-top-500
