### ISSUE TITLE
Running fish with sudo changes the ownership of the universal variables file to root

### ISSUE THREAD

**Issue by Raimondi** [fish-shell/fish-shell#2176]
When fish is run with root privileges and it writes a universal variable to disk it makes root the owner of the universal variables file. Running this command:

````fish
sudo fish -c 'set -U foobar'
````
causes this result:

````fish
$ ls -l ~/.config/fish/fishd.*
-rw------- 1 root staff 937 Jul  9 17:04 <$HOME>/.config/fish/fishd.<machine ID>
````
I used `git bisect` with the tag 2.1.2 as the good commit since it doesn't behave like this, and at first it pointed to 20d7a142c54db5a4680c21e7d464b1a5aa8aae35, which just enables fishd-less mode by default. So, I ran another `git bisect` with that mode enabled and it pointed to d7f22a0c27cb565bdd010c7ae352d5e7afc4922e.

I asked a linux user to reproduce it and he couldn't, so I'm not sure if it's just me. I use OS X 10.10.4 and fish built from the latest github source.

The script used for `git bisect run` is the following:

````fish
#!/usr/bin/env fish

# First bisect points to 20d7a142c54db5a4680c21e7d464b1a5aa8aae35 that
# basicaly does this:
sed -i '' '/return bool_from_env_var(UNIVERSAL_USE/s/true/false/' env_universal_common.cpp

set install_dir $HOME/test
set uvars_file ~/.config/fish/fishd.685b35be5d83

./configure --prefix=$install_dir
make clean
make install
# Restore modified file to avoid errors while bisecting.
git checkout -f
set -e -U foobar
sudo $install_dir/bin/fish -c "set -U foobar"
ls -l $uvars_file
if test -r $uvars_file
  exit 0
else
  # Restore ownership.
  sudo chown $USER $uvars_file
  exit 2
end
````

**Comment by zanchey** [comment]
I suspect this is because the default `sudo` configuration on OS X contains:
```
Defaults        env_keep += "HOME MAIL"
```
whereas on my Debian system the HOME variable is reset to that of the root user.

**Comment by ridiculousfish** [comment]
Any suggestions for what fish ought to do in this case?

**Comment by zanchey** [comment]
I think this happens because of the temp-file shuffle that fish uses to save its history; bash just opens the file with O_APPEND, which preserves the existing owner and permissions.

Perhaps fish could check if the history file is owned by the current euid, and alter behaviour accordingly if it isn't?

**Comment by ridiculousfish** [comment]
It would be nice to clone the existing permissions/owner when replacing the file. Linux's `chmod` has the `--reference` option to do just that.  I should look into how that works.

**Comment by kairuku** [comment]
I had a similar issue today after trying for a second time in about a month to upgrade fish (on Arch) from 2.1.2-1 => 2.2.0-3 and then had to downgrade fish again.

I have terminator start fish by default as my normal user and then often from there enter `su -c fish` to become root and not have to separately start a new fish shell (btw, this command never worked for me on Ubuntu, some complaint about a tty if I recall correctly, but it has always worked fine on Arch until I upgraded to 2.2).

Affter I upgrade, when I `su` it seems to either overwrite the universal variables file with a new version owned by root, or change ownership of the file to root. Thereafter anytime I open terminator/fish, I get this error:
```
Unable to open universal variable file [filename] Permission denied
```
Incidentally, until June my universal variables file was named fishd.0021cc6b66ff and that file has not been modified since then, I'm guessing this was around the first time I tried to upgrade to 2.2. Now the name is fishd.[hostname], and even if I delete the newly created file, after downgrading to 2.1, it still ignores the old file and creates a new one with the new naming scheme. I don't know how much difference this makes, if any?

**Comment by jeremiejig** [comment]
Hello,

I'm running on Ubuntu 14.04, and just upgraded to fish 2.2.0, I'm confirming this problem.

**Comment by faho** [comment]
@ridiculousfish: I think this needs the same treatment as #2335 - or has that already been done?

**Comment by ridiculousfish** [comment]
Quite right!

**Comment by ridiculousfish** [comment]
Fixed as f086bc95647212287415bc847fd519f484f494ff. Thanks for filing this!

**Comment by neolectron** [comment]
i'm sorry but i'm still having this error spammed on osx with nfs.
`Unable to open universal variable file '/nfs/xxx/.config/fish/fishd.10ddb1a42290': Operation not supported`.
config :
-OSX el-captain
-rootless brew
-fish 2.3.1
-nfs

**Comment by zanchey** [comment]
@neolectron, that sounds like a separate problem - would you open a new issue?
