### ISSUE TITLE
function … --wraps broken

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#2466]
The `--wraps` parameter seems to have no effect when a function is read from a fish file. I would expect it to behave like it was executed on the command line. See the following example which demonstrates the issue:

1. Put a command with the following signature into `~/.config/fish/functions/`: `function example --wraps somefunction`
2. Start a new fish
3. Try to autocomplete some parameters of the wrapper command
4. It does not work

![example](https://cloud.githubusercontent.com/assets/209270/10351104/02406e3a-6d48-11e5-8fd4-56ed3a22d030.gif)

**Comment by faho** [comment]
This is an issue with autoloading - since fish hasn't loaded the function yet, it doesn't know that it wraps something else.

Try executing it once, then completion should work.

Maybe we should also load functions on completion?

**Comment by TimWolla** [comment]
> This is an issue with autoloading - since fish hasn't loaded the function yet, it doesn't know that it wraps something else.
I'm wondering: How does it know that the function exists then (it is blue, instead of red)?
> Try executing it once, then completion should work.
It does. 
> Maybe we should also load functions on completion?
Sounds sane to me.

**Comment by ridiculousfish** [comment]
> How does it know that the function exists then (it is blue, instead of red)?

It checks the filenames in the functions directory. :/

**Comment by ridiculousfish** [comment]
What's supposed to happen in this case is that it does autoload the file. I need to check why that's not working.

**Comment by ridiculousfish** [comment]
Oh, my mistake; it autoloads the completions, but not the function itself.

**Comment by ridiculousfish** [comment]
Should be fixed as d9d2f61ba6ecb9ac26bfbc0d1e52e899a60971c5. Thanks for reporting this!

**Comment by urxvtcd** [comment]
Experiencing this with fish 2.6.0 on Arch Linux box, with a twist however: executing the command once doesn't fix it as @faho suggested.

**Comment by faho** [comment]
>executing the command once doesn't fix it as @faho suggested.

@urxvtcd: That means there's something else going on. How exactly have you defined the function? What does it wrap, and how is that defined?

**Comment by urxvtcd** [comment]
Oh, sorry, I now realize the issue is a bit different. Anyway, I defined the function as such:

	function foo --wraps git
		git $argv
	end

and it works ok. However when I `funcsave` the completion doesn't work in new fish instance.

**Comment by zanchey** [comment]
Sorry to necro this thread, but @urxvtcd never got an answer - the problem is #1625 (see also #6050 for an identical problem).
