### ISSUE TITLE
Fish does not split arguments in brackets

### ISSUE THREAD

**Issue by Samuel-Phillips** [fish-shell/fish-shell#2485]
```
> fish --version
fish, version 2.1.1
> function showargs
    echo \($argv\)
end
> showargs one two three four
(one) (two) (three) (four)
> showargs one [two three] four
(one) ([two) (three]) (four)
> showargs one t[wo three] four
(one) (t[wo three) (four)
```

Arguments are being joined together when a `[` is embedded in an argument, but not when an argument starts with it.

**Comment by faho** [comment]
I can confirm this with fish 2.2.0. It seems like a parser error to me - if I'm not missing anything, we're only using brackets for array indices (i.e. `$alist[1]`).

The workaround is trivial - escape the left or both brackets (escaping just the right will error out) or quote the left or both expressions. To be clear, this is not needed once the expressions have been stored in a variable.

To a certain degree, this is also mentioned in the documentation - it says:

>'\[' escapes the left bracket character

but it's not mentioned that it would be necessary in this case, because the behavior itself - that brackets can cause grouping under certain circumstances - isn't mentioned and seems wrong.

**Comment by cben** [comment]
Consider instead making `[a b]` always one word.
I think the word-splitting rules will become simpler: spaces between [...] never end a word.
(And if we ever change `foo.{c h}` instead/in addition to `foo.{c,h}`, they'd become extremely consistent "spaces within all kinds of brackets [({ don't end words".)

But the real reason I'm proposing this is TCL-influenced:
Having a lexer-blessed way to write a "sequence" that's parsed as one word opens the door for nested data structures.  The way we already expand things — but all within one "top-level word" — within brackets in `$a[$index $array (seq 10 20)]` is very good for that.
Even without nested structures, being able to pass 2 arrays to a command would be neat.  E.g. I've toyed with the idea that `set [frob knob blob] $argv`, or `for [k v] in [1 one] [2 two]` would do destructuring assignment...

**Comment by krader1961** [comment]
I don't understand your last comment, @cben, about being able to "pass 2 arrays" to a function. If a bracketed expression is parsed as a single word then the function gets a single word. You imply the function then needs to parse that word to extract the real arguments; e.g., __k__ and __v__ and __1__ and __one__ from your example. That breaks existing semantics. Or is your intent that the parser still breaks those arguments into potentially nested arrays?  In which case `[a b]` cannot be treated as one word by the parser which seems to contradict your first sentence.

I agree with @faho that this appears to be a too permissive parser bug. The parser should only treat brackets specially if a variable is the current scope. It should otherwise treat the left-bracket as a normal, non-special, character.

**Comment by cben** [comment]
[Long brain dump ahead.]

My “nested data” idea is still very much half-baked, despite rotating in my
head for years.
While researching this I realized I can implement most of what I want with
functions — the syntax won’t be [a b] but e.g. (L a b) but it will behave
better. I’m gonna try that based on a JSON representation and
https://stedolan.github.io/jq/ and live with them for some time…

I also encountered many non-orthoganalities in the way indexing currently
works — I’d rather see any of these made more consistent, than cater to my
pie-in-the-sky ideas:

   -

   For most purposes, {a,b}, (echo a; echo b) and $var_of_a_b are
   equivalent and interchangable in fish. That’s wonderful.
   -

   Indexing is currently supported on $var[...] and (command)[...]. {a,b}[2]
   doesn’t work (expands to a[2] b[2]); it’s hard to think of any use for
   such construct but why not…
   -

   $var[...] indexing is quite flexible in its contents: $a[1],
$a[11..20], $a[(echo
   2)] and $a[$two] all work. So do $a[$two..$three], $a[(echo 2..3)]
and $a[(echo
   2)..(echo 3)]. However $a[{10,20}] doesn’t.

   Nested indexing works but only at the end: $a[$two[1]] and $a[5 $two[1]]
   work, $a[5 $two[1] 7], $a[$two[1] 7] and $a[$two[1] $two[1]] are all
   errors.
   -

   Mixing computed indexes and spaces — $a[1 (seq 40 42) 99] behaves IMHO
   in a surprising and unuseful way, resulting in 01 40 99 01 41 99 01 42 99.
   See extended examples towards the end. When I say “surprising”, I mean I
   can now guess how its defined and see why that’s the result, but I doubt
   that’s what anyone writing this expression would mean.
   -

   (command)[...] indexing only seems to support literal numbers and
   slices: (echo a)[1], (echo a\nb\nc\nd)[2..-2] work but (echo
   a\nb\nc)[$two[1]], (echo a\nb\nc)[$two[1]] and (echo a\nb\nc)[(echo 2)]
   are syntax errors. I suspect that’s due to the above point, to
prevent (cmd)[(seq
   2)] from first expand it to (cmd)[1] (cmd)[2] and running the command
   multiple times?

------------------------------

Back to the bug here. I think we all agree that [a b] and prefix[a b] must
behave similarly. I see 3 options:

   1.

   The implied proposal here was to parse both as separate words i.e.
   prefix[a, b] (as [a, b] already does).
   Brackets would gain their space-containing powers ONLY in indexing
   constructs — $var[ ... ], (cmd)[ ... ] (and possibly {bra,ces}[ ... ]).
   2.

   My proposal above was instead to parse as one [a b] or prefix[a b] word.
   But I now see this raises the question how exactly [$var (cmd)] would
   behave — we should first decide if we like how $a[$var (cmd)] works (I
   certainly don’t).

   Also, to be sane I’d want to count nested (unescaped) brackets, i.e. p[a
   [b escaped\]doesnt count c] d] should parse as one word. Currently it
   parses as 2 words p[a [b escaped]doesnt count c] and d]. Option 1 didn’t
   have to deal with this question because [ was either a regular char or part
   of indexing, and brackets were not legal within indexes (well, $a[$b[1]]
   is legal though inconsistently, see above).
   3.

   There is a middle ground: make words with unmatched (unescaped) brackets
   e.g. x[y or z]w an error, like {y or z}w currently are.
   Then we can later relax it to either meaning. The point is not just to
   buy time; it’s the safest transition strategy in any case — instead of some
   code silently changing its meaning, a period where it gives an error will
   hopefully educate users and make them rewrite such code, so later adopting
   a different meaning should be safe.

------------------------------

On my half-baked idea:
I’m in no way suggesting a magic way to store or pass real nested
structures into functions; the interface must remain a flat unix argv. The
only way to pass structured data in a single argument is encode it into a
string according to some convention, which means commands/functions will
have to know the convention and unpack it themselves.
The exact convention is the half-baked part :-) But is must be *robust* —
one that can represent *any* data by some kind of escaping as needed.

TCL’s prior art [http://wiki.tcl.tk/440#pagetocb60556e9] had 2 crucial
insights: (A) Several layers of packing nested structures into a single
string typically results a snowball of backslashes — but it can be almost
entirely avoided by having *matched quoting chars* ({ and } in TCL); (B)
Pack lists in such a way that the language’s evaluation rules will
unpack/unescape them into individual components.

Actually fish just gained the latter ability with string escape. Here is
how a for loop over pairs can be implemented today: (*untested*, I’m still
on 2.2.0):

alias L string escape
# The outer escape is unnecessary, just to demonstrate 2 levels of
packing into single string
set pairs1 (L (L foo 'Fred Flintstone') (L bar 'Barney Rubble'))
# unpack outer level back into array
eval set pairs $pairs1

for pair in $pairs
    eval set kv $pair
    set k $kv[1]
    set v $kv[2]
    echo Do something with $k, $v...
end

Caveat: building on eval to unpack data is dangerous! It’s safe when it
comes from string escape but if not it might contain ; rm -rf / which eval
will happily run.
(TCL has safe list manipulation builtins which use the word splitting rules
but never execute anything.)

Several years ago I was confident unix doesn’t have any widely accepted
packing convention so we should design our own, well-fitting into fish.
*And the sole reason I’m thinking of using […] for that is that in some
situations brackets already do sort-of quoting in fish, and don’t have any
active meaning.*
Nowdays, I wonder if it isn’t better to adopt JSON. I’m not aware of any
command that takes JSON in an *argument* but more and more programs
consume/emit it on stdin/out. Here is the same loop with jq:

$ for pair in (echo '[["foo","Fred Flintstone"], ["bar","Barney
Rubble"]]' | jq --compact-output '.[]')
        set k (echo $pair | jq --raw-output .[0])
        set v (echo $pair | jq --raw-output .[1])
        echo Do something with $k, $v...
    end
Do something with foo, Fred Flintstone...
Do something with bar, Barney Rubble...

Both loops also suffer from lack of destructuring assignment; currently the
only way in fish to assign sevaral variables simultaneously is read but its
splitting is unsuitable.

=> New plan: forget my syntax-change

It turns out how I always imagined/wanted brackets work differs from how
they actually work.
I think I saw that $array[1 2 3], $array[$indexes] and $array[(seq 3)] all
work and presumed the content between brackets is handled *recursively*
like a command line — word split, expanded, used as a list of indexes.
But that’s an illusion — [1 2] are really supported, the other syntaxes are
by-product of the whole thing getting expanded first. The illusion breaks
if I mix spaces with expansions:

$ set a (seq -w 1 99)

$ set indexes 40 41 42
$ echo a[1 $indexes 99]   # simple expansion
a[1 40 99] a[1 41 99] a[1 42 99]
$ echo $a[1 $indexes 99]  # indexing
01 40 99 01 41 99 01 42 99

$ echo a[1 (seq 40 42) 99]   # simple expansion
a[1 40 99] a[1 41 99] a[1 42 99]
$ echo $a[1 (seq 40 42) 99]  # indexing
01 40 99 01 41 99 01 42 99

$ echo a[1 {40,41,42} 99]   # simple expansion
a[1 40 99] a[1 41 99] a[1 42 99]
$ echo $a[1 {40,41,42} 99]  # indexing
Invalid index value
fish: echo $a[1 {40,41,42} 99]
                ^

# The last error slightly breaks the usual $array–(command)–{braces}
equivalence.

# Extra credit riddles:

$ echo a[(echo 1\n2) (echo 5\n6)]   # expansion — cross product.
a[1 5] a[1 6] a[2 5] a[2 6]
$ echo $a[(echo 1\n2) (echo 5\n6)]  # indexing.
01 05 01 06 02 05 02 06
$ echo a[(echo 1\n2)(echo 5\n6)]  # expansion — cross product.

a[15] a[16] a[25] a[26]
$ echo $a[(echo 1\n2)(echo 5\n6)]  # indexing — unexplainable by the
expansion above!
01 05 01 06 02 05 02 06

But when building lists, I do want a result of “1 40 41 42 99”. And I can
have that *today* using some functions e.g. (L 1 (seq 40 42) 99) would
behave *exactly* as I want. I can even write an easier destructuring-set
function. I can’t have a custom destructuring for but I can produce | while
custom-read var1 var2 varrest…
So I’m gonna write a few, probably based on JSON, live with them for a time
and see how it feels…
​

**Comment by cben** [comment]
[Edit: destroyed mailed comment, pasted clean markdown to fix formatting.  Sorry for the noise.]
[Long brain dump ahead.]  

My "nested data" idea is still very much half-baked, despite rotating in my head for years.  
While researching this I realized I can implement most of what I want with functions — the syntax won't be `[a b]` but e.g. `(L a b)` but it will behave better.  I'm gonna try that based on a JSON representation and https://stedolan.github.io/jq/ and live with them for some time...

I also encountered many non-orthoganalities in the way indexing currently works — I'd rather see any of these made more consistent, than cater to my pie-in-the-sky ideas:

- For most purposes, `{a,b}`, `(echo a; echo b)` and `$var_of_a_b` are equivalent and interchangable in fish.  That's wonderful.

- Indexing is currently supported on `$var[...]` and `(command)[...]`.  `{a,b}[2]` doesn't work (expands to `a[2] b[2]`); it's hard to think of any use for such construct but why not...

- `$var[...]` indexing is quite flexible in its contents: `$a[1]`, `$a[11..20]`, `$a[(echo 2)]` and `$a[$two]` all work.  So do `$a[$two..$three]`, `$a[(echo 2..3)]` and `$a[(echo 2)..(echo 3)]`.  However `$a[{10,20}]` doesn't.

    Nested indexing works but only at the end: `$a[$two[1]]` and `$a[5 $two[1]]` work, `$a[5 $two[1] 7]`, `$a[$two[1] 7]` and `$a[$two[1] $two[1]]` are all errors.

- Mixing computed indexes and spaces — `$a[1 (seq 40 42) 99]` behaves IMHO in a surprising and unuseful way, resulting in 01 40 99 01 41 99 01 42 99.  See extended examples towards the end.  When I say "surprising", I mean I can now guess how its defined and see why that's the result, but I doubt that's what anyone writing this expression would mean.

- `(command)[...]` indexing only seems to support literal numbers and slices: `(echo a)[1]`, `(echo a\nb\nc\nd)[2..-2]` work but `(echo a\nb\nc)[$two[1]]`, `(echo a\nb\nc)[$two[1]]` and `(echo a\nb\nc)[(echo 2)]` are syntax errors.  I suspect that's due to the above point, to prevent `(cmd)[(seq 2)]` from first expand it to `(cmd)[1] (cmd)[2]` and running the command multiple times?

-----

Back to the bug here.  I think we all agree that `[a b]` and `prefix[a b]` must behave similarly.  I see 3 options:

1. The implied proposal here was to parse both as separate words i.e. `prefix[a`, `b]` (as `[a`, `b]` already does).
   Brackets would gain their space-containing powers ONLY in indexing constructs — `$var[ ... ]`, `(cmd)[ ... ]` (and possibly `{bra,ces}[ ... ]`).

2. My proposal above was instead to parse as one `[a b]` or `prefix[a b]` word.
    But I now see this raises the question how exactly `[$var (cmd)]` would behave — we should first decide if we like how `$a[$var (cmd)]` works (I certainly don't).

    Also, to be sane I'd want to count nested (unescaped) brackets, i.e. `p[a [b escaped\]doesnt count c] d]` should parse as one word.  Currently it parses as 2 words `p[a [b escaped]doesnt count c]` and `d]`.  Option 1 didn't have to deal with this question because [ was either a regular char or part of indexing, and brackets were not legal within indexes (well, `$a[$b[1]]` is legal though inconsistently, see above).

3. There is a middle ground: make words with unmatched (unescaped) brackets e.g. `x[y` or `z]w` an error, like `{y` or `z}w` currently are.
   Then we can later relax it to either meaning.  The point is not just to buy time; it's the safest transition strategy in any case — instead of some code silently changing its meaning, a period where it gives an error will hopefully educate users and make them rewrite such code, so later adopting a different meaning should be safe.

-----

I'm in no way suggesting a magic way to store or pass real nested structures into functions; the interface must remain a flat unix argv.  The only way to pass structured data in a single argument is encode it into a string according to some convention, which means commands/functions will have to know the convention and unpack it themselves.
The exact convention is the half-baked part :-)  But is must be *robust* — one that can represent *any* data by some kind of escaping as needed.

TCL's prior art [http://wiki.tcl.tk/440#pagetocb60556e9] had 2 crucial insights: (A) Several layers of packing nested structures into a single string typically results a snowball of backslashes — but it can be almost entirely avoided by having *matched quoting chars* (`{` and `}` in TCL); (B) Pack lists in such a way that the language's evaluation rules will unpack/unescape them into individual components.

Actually fish just gained the latter ability with `string escape`.  Here is how a for loop over pairs can be implemented today: (*untested*, I'm still on 2.2.0):
```
alias L string escape
# The outer escape is unnecessary, just to demonstrate 2 levels of packing into single string
set pairs1 (L (L foo 'Fred Flintstone') (L bar 'Barney Rubble'))
# unpack outer level back into array
eval set pairs $pairs1

for pair in $pairs
    eval set kv $pair
    set k $kv[1]
    set v $kv[2]
    echo Do something with $k, $v...
end
```
Caveat: building on `eval` to unpack data is dangerous!  It's safe when it comes from `string escape` but if not it might contain `; rm -rf /` which `eval` will happily run.
(TCL has safe list manipulation builtins which use the word splitting rules but never execute anything.)

Several years ago I was confident unix doesn't have any widely accepted packing convention so we should design our own, well-fitting into fish.
**And the sole reason I'm thinking of using [...] for that is that in some situations brackets already do sort-of quoting in fish, and don't have any active meaning.**
Nowdays, I wonder if it isn't better to adopt JSON.  I'm not aware of any command that takes JSON in an *argument* but more and more programs consume/emit it on stdin/out.  Here is the same loop with jq:
```
$ for pair in (echo '[["foo","Fred Flintstone"], ["bar","Barney Rubble"]]' | jq --compact-output '.[]')
        set k (echo $pair | jq --raw-output .[0])
        set v (echo $pair | jq --raw-output .[1])
        echo Do something with $k, $v...
    end
Do something with foo, Fred Flintstone...
Do something with bar, Barney Rubble...
```
Both loops also suffer from lack of destructuring assignment; currently the only way in fish to assign sevaral variables simultaneously is `read` but its splitting is unsuitable.

=> New plan: forget my syntax-change

It turns out how I always imagined/wanted brackets work differs from how they actually work.
I think I saw that `$array[1 2 3]`, `$array[$indexes]` and `$array[(seq 3)]` all work and presumed the content between brackets is handled *recursively* like a command line — word split, expanded, used as a list of indexes.
But that's an illusion — `[1 2]` are really supported, the other syntaxes are by-product of the whole thing getting expanded first.  The illusion breaks if I mix spaces with expansions:
```
$ set a (seq -w 1 99)

$ set indexes 40 41 42
$ echo a[1 $indexes 99]   # simple expansion
a[1 40 99] a[1 41 99] a[1 42 99]
$ echo $a[1 $indexes 99]  # indexing
01 40 99 01 41 99 01 42 99

$ echo a[1 (seq 40 42) 99]   # simple expansion
a[1 40 99] a[1 41 99] a[1 42 99]
$ echo $a[1 (seq 40 42) 99]  # indexing
01 40 99 01 41 99 01 42 99

$ echo a[1 {40,41,42} 99]   # simple expansion
a[1 40 99] a[1 41 99] a[1 42 99]
$ echo $a[1 {40,41,42} 99]  # indexing
Invalid index value
fish: echo $a[1 {40,41,42} 99]
                ^
# The last error slightly breaks the usual $array–(command)–{braces} equivalence.

# Extra credit riddles:

$ echo a[(echo 1\n2) (echo 5\n6)]   # expansion — cross product.
a[1 5] a[1 6] a[2 5] a[2 6]
$ echo $a[(echo 1\n2) (echo 5\n6)]  # indexing.
01 05 01 06 02 05 02 06
$ echo a[(echo 1\n2)(echo 5\n6)]  # expansion — cross product.
a[15] a[16] a[25] a[26]
$ echo $a[(echo 1\n2)(echo 5\n6)]  # indexing — unexplainable by the expansion above!
01 05 01 06 02 05 02 06
```

But when building lists, I do want a result of "1 40 41 42 99".  And I can have that *today* using some functions e.g. `(L 1 (seq 40 42) 99)` would behave *exactly* as I want.  I can even write an easier destructuring-set function.  I can't have a custom destructuring for but I can `produce | while custom-read var1 var2 varrest`...
So I'm gonna write a few, probably based on JSON, live with them for a time and see how it feels...

**Comment by mqudsi** [comment]
This is an artifact of the support for bash's `[` alias for `test`, which gets treated as a regular character (i.e. a command-valid grammar component) when used at the head of a token, but is otherwise a reserved character for array indexing (aka "the slice operator").

Use of an escaped or unquoted bracket should be avoided, it should be a tokenization or parser error if used not in conjunction with an array or as the special `test` alias.

**Comment by faho** [comment]
This appears to have been fixed, possibly via #3802?

Can anyone else confirm?

**Comment by mqudsi** [comment]
@faho still there

```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> function showargs
                                        echo \"$argv\"
                                    end
mqudsi@ZBook /m/c/U/m/r/fish-shell> showargs one t[wo three] four
"one" "t[wo three]" "four"
mqudsi@ZBook /m/c/U/m/r/fish-shell> showargs one [two three] four
"one" "[two" "three]" "four"
```

**Comment by mqudsi** [comment]
This PR has a lot of different test cases, the behavior of some of which was changed in #3802 with the changes to `src/tokenizer.cpp`, but the basic issue remains in that there is ambiguous syntax that is split differently depending on what way you squint and look at it, primarily demonstrated with the following:

```fish
~> function showargs
          echo \"$argv\"
      end
~> showargs one [two three] four
"one" "[two" "three]" "four"
~> showargs one t[wo three] four
"one" "t[wo three]" "four"
```

**Comment by mqudsi** [comment]
@cben this is an attempt at addressing this issue, if you'd like to try it out: https://github.com/fish-shell/fish-shell/pull/5228

The shell does some enforcement of balancing, but doesn't tokenize.. which should be somewhat along the lines of something you were looking for.

**Comment by cben** [comment]
Cool!  Testing your branch from #5228...

This is pretty close to option (2) in my way-too-long comment above, except for special casing lone `[` (which I hadn't taken into account then).
Obviously the `[` alias of `test` must remain parsed as a standalone word :+1:

But while this solves the `[two` vs `t[wo` inconsistency, but special treatment of lone `[` still feels surprising:
```
# PR #5228 — fish, version 2.7.1-1506-g703adec9
$ showargs one t[wo three] four
(one) (t[wo three]) (four)
$ showargs one [two three] four
(one) ([two three]) (four)
$ showargs one [ two three] four
(one) ([) (two) (three]) (four)
$ showargs one [two three ] four
(one) ([two three ]) (four)
$ showargs one [ two three ] four
(one) ([) (two) (three) (]) (four)
```
Beside lone `[` being special, the asymmetry between `[` and `]` also feels surprising.  It also shows up in "unbalanced" errors:
```
$ showargs [3 = 3]]]]   # no problem!
([3 = 3]]]])
$ showargs [[[[3 = 3]
fish: Unexpected end of string, square brackets do not match
showargs [[[[3 = 3]
         ^
```

=> For simplicity and consistency or regular tokenization, I'm afraid option (1) is a clear winner — treat brackets as regular symbols in all uses except indexing.  It would look like this:
```
# fictional proposed behavior
$ showargs one t[wo three] four
(one) (t[wo) (three]) (four)
$ showargs one [two three] four
(one) ([two) (three]) (four)
$ showargs one [ two three] four
(one) ([) (two) (three]) (four)
$ showargs one [two three ] four
(one) ([two) (three) (]) (four)
$ showargs one [ two three ] four
(one) ([) (two) (three) (]) (four)

$ showargs [3 = 3]]]]
([3) (=) (3]]]])
$ showargs [[[[3 = 3]
([[[[3) (=) (3])
```

Now what about consistency between text `a[...]` vs indexing `$a[...]`?
Is such consistency even a goal?
They're now similar but don't fully match; AFAICT, #5228 doesn't change anything there; option (1) would make them less similar.
=> IMHO not a goal.  The current behavior of indexing is far from my ideal, which requires recursive parsing and could not be equivalent to _any_ tokenization anyway.

To keep this focused, I'll open a separate issue for how I'd like indexing to work.  For this issue, ignore my previous suggestions to parse `[1 2]` as one word, I now support option (1).

**Comment by Nahor** [comment]
> $ showargs one t[wo three] four
> (one) (t[wo) (three]) (four)

Note that currently `set` relies on the combined arg for indexed variables (e.g. `set foo[1 2] first second`), though it wouldn't be hard for it to recombined the split args on its own and as necessary.
