### ISSUE TITLE
Using help on a builtin command dies when trying to send you to an html page

### ISSUE THREAD

**Issue by Soares** [fish-shell/fish-shell#342]
I'm brand new to fish. As a dvorak user I wanted to rebind Crtl-F to something a bit easier to type. So I type `help bind`, and get:

```
So8res ~> help bind
Warning: unknown mime-type for "/usr/local/share/doc/fish/commands.html#bind" -- using "application/octet-stream"
Error: no such file "/usr/local/share/doc/fish/commands.html#bind"
```

The file `/usr/local/share/doc/fish/commands.html` definitely exists, it looks like the hash is throwing off python's `webserver.open()`, which is grabbing google-chrome, as it were.

**Comment by cben** [comment]
For me on Lubuntu 15.04 `help for` is still broken.
I have gvfs-open installed but just having it doesn't automagically help (perhaps because I'm running LXDE rather than Gnome session?).
In any case, 

    gvfs-open 'file:///usr/share/doc/fish/commands.html#for'

works while

    gvfs-open '/usr/share/doc/fish/commands.html#for'

fails.
Same is true for `sensible-browser` though for different reason: without `file://` prefix it takes `#` to be part of the filename (opening file:///usr/share/doc/fish/commands.html%23for) but with file:// prefix it takes it as hash fragment.

Perhaps we can amend `help` to try `gvfs-open` and/or `sensible-browser` in preference to `xdg-open`?

**Comment by faho** [comment]
@cben: Is this an issue with fish 2.2.0? It uses the "file://" prefix so it should work.

**Comment by faho** [comment]
I'm now assuming this is fixed since we use the "file://" prefix.

**Comment by zanchey** [comment]
It actually doesn't work, even in 2.2.0 - but `xdg-open` is at fault, not fish. I don't think checking for `gvfs-open` is wise as that may be present on systems even if you are not running GNOME, but `sensible-browser` is a good idea as that will work on all Debian-derived systems. The only problem is that there's no way to know whether it will start a graphical browser or a text-mode browser.

**Comment by cben** [comment]
Still a problem.  Now on Lubuntu 15.10, fish 2.2.0-2, xdg-utils 1.1.0~rc3+git2015090.
strace confirms fish executes:
```
30708 execve("/usr/bin/xdg-open", ["xdg-open", "file:///usr/share/doc/fish/commands.html#bind"], [/* 73 vars */] <unfinished ...>
```
For me (LXDE desktop), this opens file browser at / dir.
Without `#bind` it does open the browser (but obviously doesn't scroll to the specific command).
`gvfs-open`, `gnome-open` and `sensible-browser` all work correctly with `#bind`.

A quick search suggest the closest reported xdg-open bug was https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800355 , fixed by http://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=5f6e3b328a1f3ccb6ec61b0193eac3e09309fcf5
Running xdg-open from git HEAD opens commands.html (without `#bind`) in my Chromium.
Which is progress but not perfect.

**Comment by krader1961** [comment]
Closing since this is a bug in an external command and it's been 4.5 years since the issue was reported and no one cared enough to implement a workaround.
