### ISSUE TITLE
error message: There is no fish_key_bindings function called: ''

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3590]
Behavior:
Fish will output:
There is no fish_key_bindings function called: ''
Keeping fish_default_key_bindings

How to reproduce:
0. make sure fish_key_bindings is not set in configuration file.
1. in tty1, run fish
2. in tty2, delete fishd.* files, run fish

tty1 will have:
There is no fish_key_bindings function called: ''
Keeping fish_default_key_bindings

**Comment by introom** [comment]
The echo here is not necessary.

https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_config_interactive.fish#L182

**Comment by faho** [comment]
That echo _is_ necessary, because it's also used in case you set a wrong bindings function, e.g. you fat-finger `set fish_key_bindings fish_defualt_key_bindings` or `set fish_key_bindings fish_iv_key_bindings`.

We may want to not print it in this case, but I'm not sure we can detect this in particular. We do want an error if you `set fish_key_bindings` without an argument, or with an empty one (like an unset variable).

Did you actually get this error by doing your reproduction steps or did you find it another way and figure out those steps to make it easier for us?

**Comment by faho** [comment]
Though now that I see it, we might want to undo the `set` if it's not working, so you don't get the error again and again.

**Comment by introom** [comment]
@faho 
>> Did you actually get this error by doing your reproduction steps or did you find it another way and figure out those steps to make it easier for us?

I did some operations that happen to contain the above steps.  I narrowed them down to the above steps.

**Comment by krader1961** [comment]
I spent some time exploring this issue. @faho's change does not fix the reported failure mode but is an improvement nonetheless. The core problem is the recursive nature of setting the `fish_key_bindings` variable given that any change to it causes the `__fish_reload_key_bindings()` function to also modify it.

**Comment by krader1961** [comment]
I think we should rework this code to avoid the tricky recursive invocation of the relevant functions due to event callbacks. That should solve this and make the logic a heck of a lot clearer.

**Comment by dpux** [comment]
I have been facing this issue since version 2.7.1. I upgraded to 3.0 but that doesn't fix the problem.
```
> uname -a
Darwin C02V80QLHTD6MBP 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

Fish-shell is installed as a default on my Mac. On launching a new terminal, this is the error I get:

```
Welcome to fish, the friendly interactive shell
There is no fish_key_bindings function called: ''
., :, N_, abbr, alias, bg, cd, cdh, contains_seq, delete-or-exit, dirh, dirs,
disown, down-or-search, edit_command_buffer, eval, export, fg,
fish_breakpoint_prompt, fish_clipboard_copy, fish_clipboard_paste, fish_config,
fish_default_key_bindings, fish_default_mode_prompt, fish_fallback_prompt,
fish_hybrid_key_bindings, fish_indent, fish_key_reader, fish_md5,
fish_mode_prompt, fish_opt, fish_print_hg_root, fish_prompt,
fish_sigtrap_handler, fish_title, fish_update_completions, fish_vi_cursor,
fish_vi_key_bindings, fish_vi_mode, funced, funcsave, grep, help, history,
hostname, isatty, kill, la, ll, ls, man, mkcdir, nextd, nextd-or-forward-word,
open, popd, prevd, prevd-or-backward-word, prompt_hostname, prompt_pwd, psub,
pushd, realpath, seq, setenv, string, suspend, trap, type, umask, up-or-search,
vared, wait,
Keeping 
<Similar lines of error>
fish: The function call stack limit has been exceeded. Do you have an accidental infinite loop?
__fish_reload_key_bindings VARIABLE SET fish_key_bindings
^
in event handler: handler for variable 'fish_key_bindings'
```


Based on other posts, broken bindings in fish_prompt.fish may result in such errors, but I don't see anything special on my machine.
**_~/.config/fish/functions/fish_prompt.fish:_**
```
function fish_prompt
	test $SSH_TTY
    and printf (set_color red)$USER(set_color brwhite)'@'(set_color yellow)(prompt_hostname)' '
    test "$USER" = 'root'
    and echo (set_color red)"#"

    # Main
    echo -n (set_color cyan)(prompt_pwd) (set_color red)'❯'(set_color yellow)'❯'(set_color green)'❯ '
end
```

**Comment by faho** [comment]
@dpux: Run this, once:

```fish
set -U fish_user_key_bindings fish_default_key_bindings
```

**Comment by dpux** [comment]
@faho 
The command you shared:
`set -U fish_key_bindings fish_default_key_bindings`
did not solve the problem, it didn't throw any error either. I restarted my machine to ensure refreshing any hidden settings I am unaware of.

```
~ ❯❯❯ set --show fish_key_bindings
$fish_key_bindings: not set in local scope
$fish_key_bindings: not set in global scope
$fish_key_bindings: set in universal scope, unexported, with 0 elements
```
I am not very familiar with bindings yet, but does the output above indicate that default key bindings have been overwritten? I don't remember installing any new software recently, or even changing the path variables. I did run homebrew update a few days ago, but it did not result in any issues back then.

**Comment by faho** [comment]
>$fish_key_bindings: set in universal scope, unexported, with 0 elements

WAT?

That's quite wrong. You _just_ set $fish_key_bindings to have one element, and now it has 0 again?

Okay, do you have a config.fish? Do you use any third-party stuff like oh-my-fish or fisher or fundle?

What does `locale` output? `set --show __fish_active_key_bindings XDG_CONFIG_HOME HOME`?

**Comment by dpux** [comment]
> set -U fish_key_bindings fish_default_key_bindings

Damn, this was a quick fix. Thanks @faho

**Comment by zanchey** [comment]
@faho, go ahead!

**Comment by faho** [comment]
93c0d3f4a.

**Comment by faho** [comment]
Okay, I can't reproduce the original issue anymore. I'm assuming it's been fixed in the meantime.
