### ISSUE TITLE
fish_config doesn't save abbreviations anymore

### ISSUE THREAD

**Issue by Vistaus** [fish-shell/fish-shell#3620]
Until recently, I was able to add abbreviations in fish_config but when I try to do it now, it just doesn't save them anymore. For example, if I add cv for convert and hit Save, it appears to have saved it. But when I close the config ('Hit Enter to Stop') it hasn't added the abbreviation and when re-opening fish_config, it really did disappear.

OS: Solus (but it also happens for me on Arch)
DE: Budgie 10.2.8
fish: Both stable and latest git master (I mean that the issue is present in both versions)
Browser: Both vivaldi-snapshot (latest) and Web (Epiphany) 3.20/3.22 (both browsers present the same issue)

**Comment by zanchey** [comment]
I wonder if there is a global variable somewhere overriding the usual universal variable store. Does `set -qg fish_user_abbreviations; or echo OK` print "OK"?

**Comment by zanchey** [comment]
Urgh, never mind, I can reproduce this on master.

**Comment by zanchey** [comment]
The behaviour that the web config tool expects was changed by 309e10e7.

**Comment by zanchey** [comment]
So, I fixed the correct case, but errors don't bubble back correctly - 20bcbcc2 is partially to blame due to changing some conditionals from `if r == True` to just `if r`, ignoring the fact that `True` was being used as a sentinel value. Removing that problem still doesn't lead to the right behaviour.

**Comment by krader1961** [comment]
As I said on Gitter the problem is the anti-pattern of returning `True` on success else an error message. That should never be done. Instead the called function should return a tuple; e.g., `(okay, errmsg)`. Alternatively in this case it can return a single value that is the error message if an error occurred else `None` or an empty string (both of which evaluate to false. That would make the broken code read

```
errmsg = self.do_remove_abbreviation(postvars)
if errmsg:
    output = [errmsg]
else
    output = ["OK"]
```

instead of

```
r = self.do_remove_abbreviation(postvars)
if r:
    output = ["OK"]
else
    output = [errmsg]
```

In python you should always be able to replace `if x == True:` with just `if x:`

**Comment by ridiculousfish** [comment]
Nice tip, I didn't know that but it makes sense.

**Comment by krader1961** [comment]
I have a change that fixes the problem mentioned in my previous comment but I still can't create an abbreviation from the web UI. No error is displayed whether or not the abbreviation is valid. So there is something else also wrong with the code.

**Comment by krader1961** [comment]
I realized I was inadvertently pressing the "x" button rather than the "save" button. So  with the change I just merged we can once again save and delete abbreviations from the web UI. However, invalid abbreviations do not display the error message even though I've confirmed it is sent in the response to the HTTP POST request. Something is wrong in the web UI javascript and I'm insufficiently motivated to figure it out. I also rolled back all the recent changes and confirmed invalid abbreviations don't result in an error displayed to the user. Someone will have to open a new issue if they're interested in fixing that seemingly long standing bug.

**Comment by blindside85** [comment]
I took a quick glance to see if I could find anything useful (since this issue is killing me right now). I ran `fish_config` and tried to add a new abbreviation, clicked 'save', and checked my network panel... the call to `save_abbreviation/` is getting this response:

```
["abbr: abbreviation cannot have spaces in the key\n"]
```

... which is occurring with keys that don't have any spaces. I'm not super familiar with Python, but I suspect the issue has to do with lines 105 and 136 in `share/functions/abbr.fish`.

I hope that helps!

**Comment by krader1961** [comment]
@blindside85, A fix was committed on Dec 4. If you're able to reproduce this problem with a version of fish built from source that includes commit 20bcbcc please open a new issue. I cannot reproduce the problem you're reporting.

**Comment by Maximebpro** [comment]
`2.5.0` does not fix the issue. As @blindside85 mentioned, it keeps getting the response:
```
["abbr: abbreviation cannot have spaces in the key\n"]
```
which by the way return a `200` where it should return a `400: Bad Request`.

**Comment by faho** [comment]
@Maximebpro: I have to say "works for me".

What are your current abbreviations? What custom functions do you have? In particular, please check that you don't have an old customized version of the "abbr" function somewhere (e.g. ~/.config/fish/functions).

Are you sure you're running the 2.5.0 version of fish_config? IIRC homebrew can sometimes mess with the paths, so we'll get the wrong version. 

Please post the output of 

- `printf '%s\n' $fish_user_abbreviations`

- `md5sum $__fish_datadir/tools/web_config/webconfig.py` 

and

```fish
for file in $fish_function_path/abbr.fish
    if test -e $file
        md5sum $file
        break
    end
end
```

**Comment by krader1961** [comment]
@Maximebpro: In addition to everything faho mentioned I'll point out the obvious. If you simply install fish 2.5.0 but do not restart all your shells you aren't actually using fish 2.5.0. Just do `exec fish` in each shell or exit and open new terminals.

**Comment by Maximebpro** [comment]
Feeling bad right now... Captain obvious was not with me... 

Restarting fish worked perfectly. Sorry for bothering and thank you very much for you help 👍
