### ISSUE TITLE
vim mode: deletion with movement to space doesn't delete

### ISSUE THREAD

**Issue by jacobsa** [fish-shell/fish-shell#4019]
I'm using fish 2.4.0 on Linux.

From zsh's vim mode I'm in the habit of deleting arguments by positioning myself at the start of the argument and then pressing `d t <space>`. In fish's vim mode this just moves me to the space, instead of deleting.

Would it be difficult to properly support deletion with a `t` movement, as in vim?

**Comment by jacobsa** [comment]
(Also in the meantime does anybody have a good workaround for deleting long arguments?)

**Comment by krader1961** [comment]
See the `fish_vi_key_bindings` script and the `bind` command. The vi bindings would need to introduce another binding sub mode that is entered when `dt` or `df` is seen. That sub mode would then delete up to (or including) the next character typed. This is certainly possible to implement and patches are welcomed to implement this behavior.

However, my recommendation is to get used to typing [meta-v] or [meta-e] to put the current command line into a real Vi editor for any non-trivial changes. That's because the fish Vi key bindings will probably never implement more than a tiny subset of Vi/Vim behaviors.

**Comment by jacobsa** [comment]
Ah, I didn't know about [meta-v]. Is there documentation for `fish_vi_key_bindings` somewhere? The best I found was a single Stack Overflow question about how to turn it on.

That said, I can't figure out what my meta key is. I'm using the macOS Terminal.app to connect over ssh to Linux, with tmux running on Linux.

**Comment by krader1961** [comment]
No, the fish key bindings are not well documented other than that they exist and how to invoke one of them. That should be improved. Patches are welcomed :smile:

The meta key in macOS Terminal.app is normally the [alt] or [option] key (depending on your keyboard). At least if the profile keyboard preferences has the "Use Option as Meta Key" is checked. That allows you to press the [alt] or [option] key and another key (e.g., `v`) to send the second key prefixed by escape. The [meta] key mechanism as a way to prefix the next key with the escape character dates back 20+ years to the Emacs editor.

**Comment by krader1961** [comment]
Also, the [meta-v] and [meta-e] bindings where introduced in fish 2.5.0 or later. So they won't be available on your system running fish 2.4.0 unless you have installed custom bindings. You can type `bind \ev` to find out if that binding exists.

**Comment by jacobsa** [comment]
Ah thanks, that explains why I haven't seen anybody mention it, and why it doesn't work. I will attempt to get fish 2.5.0 and try it out. Thanks!

**Comment by jacobsa** [comment]
@krader1961: I don't think this should be closed. It's still a surprising inconsistency with vim. Using [meta-v] works as a workaround, but doesn't fix the problem.

**Comment by krader1961** [comment]
Reopening since the O.P. was asking for an enhancement, not just asking a question. However, note that there are a zillion features of Vim and 99.99% of them will never be implemented. For example, named buffers will probably never be implemented and that feature goes back to the very first vi implementation. So the question is which vi/vim features are so essential that they need to be native to fish? This may be such a feature. But it's going to require someone who is motivated, like yourself @jacobsa, to implement it.

**Comment by krader1961** [comment]
Note, too, that it isn't just the deletion key sequences like `dt` that need to be implemented. It's also the change text sequences like `ct`.

**Comment by e-beach** [comment]
Another note on this, the semicolon operator doesn't work in vi mode, which is surprising because it does work in vi mode for the bash shell.

**Comment by e-beach** [comment]
Another note on this, the `;` motion for repeating `f/F/t/T` does not work, which is surprising because it does work in bash's vi mode.

**Comment by krader1961** [comment]
@e-beach, The reason this works in bash is that it uses the mature GNU readline library. Fish does not use that library and instead uses a home grown mechanism better suited to its needs. Fish also does not support count prefixes (no idea if readline does). Fish will never use readline so the only way things like `;` will be implemented is if someone who is motivated like yourself submits a patch for review.

As I said earlier there are literally thousands of Vi features, let alone Vim features, not supported by fish and probably never will be supported. Some, like a binding for the `;` movement operator could probably be implemented with a modest amount of effort. And doing so would probably make it easier to implement other Vi features that depend on remembering the state after the previous editing command. At the moment the fish vi editing behavior is mostly stateless which is why features like the `;` movement command don't work.

**Comment by mqudsi** [comment]
I've toyed with the idea of exploring neovim's msgpack api to relegate all vim features to there, but vim in the shell isn't important enough for me to spend the time that would take to experiment with.

**Comment by krader1961** [comment]
> ... but vim in the shell isn't important enough for me to spend the time that would take to experiment with.

Bingo. That is true for 99.999% of fish users. Which is why these types of features are unlikely to ever get implemented. And I say that as someone who used to use Emacs but has used vi/nvi/vim daily for 20+ years due to a job I had long ago where I could not expect emacs to be available. Which is why I made it easy to drop into a real Vi editor via the \ee and \ev key bindings since I too recognize that fish's support vi editing lacks lots of features I expect to be available.

**Comment by dgsb** [comment]
Can someone elaborate why the readline library will never be used ? Wouldn't it be easier to integrate rather than implement the same functionality ?

**Comment by ridiculousfish** [comment]
I don't know how easy it would be to implement things like autosuggestions, fish's history, etc. on top of readline. It might make some things easier and other things harder.

**Comment by linsomniac** [comment]
I understand that all of vim isn't going to be implemented, but "dtX" and "ctX" feel to me like a pretty core part of the emulation and are something I miss on a daily basis that makes fish feel like an incomplete vi-experience shell, and have nearly made me give up on fish.  The ESC-e to bring up the editor will work as a kludge.  :-)

**Comment by duckworthd** [comment]
Just wanted to +1 this issue. I use vi-mode daily, and I find myself using `cf<space>` quite frequently unexpected results!

Vim has a lot of features that don't don't need to be re-implemented, but this is one I would definitely be delighted to see.

**Comment by arael** [comment]
This is the only reason I have not switched yet. It disrupts my workflow. I like most of the fish shell features but the vi-mode is simply poor. I will switch the day this is added and every time a new version is out I try.
Please implement this, it is important for the vi users. We might be a minority but we exist.

**Comment by butterfly-pn** [comment]
Actually is it possible at all to move cursor like `5h`? I think it's also essential in vi mode.
Except that I would like also to +1 this issue

**Comment by tsoernes** [comment]
I also have the issue that `d0` does not work. The cursor moves to the beginning of the line, but no text is deleted. `db` works. 
```
 !  ~/progs  bind 0
bind --preset 0 beginning-of-line
 !  ~/progs  fish --version
fish, version 3.0.2
```

**Comment by gokulsoumya** [comment]
> (Also in the meantime does anybody have a good workaround for deleting long arguments?)
@jacobsa You can use `^W` for that, which by default maps to `backward-kill-path-component`

**Comment by Aster89** [comment]
Well, not even the ever-green `.` works, which is a bit disappointing.

However, since some things like `de` work (`dw` mistakenly does the same), I guess it could be easy for someone to dive into the code and fix/add text object for delete and other actions.

I don't feel confident enough to take this on, but I would at least give a look at it, if someone could at least tell me _here it is the file that you can play a bit to see what you can get_ (assuming that the implementation of such things is really localized to a single file, for the sake of the argument).

**Comment by krobelus** [comment]
> if someone could at least tell me here it is the file that you can play a bit

Interactive commandline editing is implemented in [src/reader.cpp](https://github.com/fish-shell/fish-shell/blob/master/src/reader.cpp).

**Comment by tjkirch** [comment]
> > ... but vim in the shell isn't important enough for me to spend the time that would take to experiment with.
> 
> Bingo. That is true for 99.999% of fish users. Which is why these types of features are unlikely to ever get implemented. [...]
> Which is why I made it easy to drop into a real Vi editor via the \ee and \ev key bindings since I too recognize that fish's support vi editing lacks lots of features I expect to be available.

I bet there are other users, like me, for whom this is very important but who don't have the C++ skills to work on the core of fish.  I'd be willing to sponsor development (via bounty or similar) to improve vi mode.  I think it's reasonable to have improved movement and basic editing support.  Yes, vim is huge, but most of it is irrelevant to a shell; I think we could get a lot of mileage out of some of the basics.  Movement, `.` repeat, undo/redo, etc.  zsh does this *very* well, and without readline.

I see that fish is on bountysource, but there's no individual issue representing something like this, and the response in issues is usually "just use meta-v" so I wouldn't know what/how to suggest.

**Comment by zanchey** [comment]
From memory the original implementation was supported by a bounty so that might be the way to go. I don't think any of the fish committers have posted anything on bountysource though.

**Comment by jacobsa** [comment]
+1, I'd pay money for vim support to be significantly better supported. The weird uncanny valley state it's currently in is probably the worst part about using fish for me.

**Comment by ridiculousfish** [comment]
One option would be to adopt zsh's vi mode implementation, which is nicely factored into `zle_vi.c` and `zle_move.c`.

**Comment by umanwizard** [comment]
> there are a zillion features of Vim and 99.99% of them will never be implemented.

We are not talking about vim, we are talking about vi. Motions like d2W are part of standard POSIX vi. Also, they are absolutely essential, not some obscure feature.

How hard would it be to make fish use readline instead of the home-grown implementation?

**Comment by faho** [comment]
> How hard would it be to make fish use readline instead of the home-grown implementation?

It won't.

Really someone just needs to work on vi-mode.

**Comment by ahillio** [comment]
Towards a feature-complete `vi mode` implementation....

Considering:
> We are not talking about vim, we are talking about vi. Motions like d2W are part of standard POSIX vi. Also, they are absolutely the core of vi, not some obscure feature.

and further back:
> I've toyed with the idea of exploring neovim's msgpack api to relegate all vim features to there, **but vim in the shell isn't important enough for me to spend the time that would take to experiment with.**

and a response:
> Bingo. That is true for 99.999% of fish users. Which is why these types of features are unlikely to ever get implemented.

I'm quite interested in a feature complete (like parity with gnu readline's vi-mode, for example) vi mode, with it's through fixing issues like this or perhaps by re-architecting this and to utilize neovim.  I wouldn't be writing the code myself but contracting it and have no idea what kind of scale project this would be.   Any guestimates?  50hours? 250?

**Comment by Aster89** [comment]
@faho, I've (only now) given a look at the `src/reader.cpp` file that I was suggested to give a look at some month ago, but I don't find much that help me understand where one can "attack" the problem. For instance, I searched for `\<emacs\>`, `\<vi\>`, `'d'`, and other things that I expected to be related to the vi-mode handling. I've also searched all `*.cpp` and `*.h` files in the repo, but I haven't been able to find more.

So my question is: what files I should look at to see how my pressing <kbd>d</kbd><kbd>w</kbd> results in calling a function which replaces some text with the empty string (which is more or less what `dw` does)?

**Comment by faho** [comment]
>For instance, I searched for \<emacs\>, \<vi\>, 'd', and other things that I expected to be related to the vi-mode handling

What `reader` does is execute the "bind functions". These are bound to different things depending on your configuration. Now, if you've chosen vi-mode, the basis of that will be in the [fish_vi_key_bindings](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_key_bindings.fish) function. E.g. if you press "dw" that currently executes [kill-word](https://github.com/fish-shell/fish-shell/blob/7da93e26176f9996a0d49cc7da2a8151c8550a36/share/functions/fish_vi_key_bindings.fish#L149), so you'd check in reader.cpp for `kill_word` (the names are translated via the [input function metadata table](https://github.com/fish-shell/fish-shell/blob/7da93e26176f9996a0d49cc7da2a8151c8550a36/src/input.cpp#L87), but typically it's just replacing dashes with underlines).

What you would have to do here is figure out a way to make "d*" *read a motion argument* to then pass on to the executed function (like kill-word for "dw") once the final character (e.g. the "w") is pressed. This includes a way to express that in configuration (we have some functions that read additional characters like IIRC forward-jump, it's possible that approach would work).

It's possible this requires actually giving reader knowledge about vi-mode, but we'd prefer if it didn't.

It's a bigger thing.

**Comment by Aster89** [comment]
@faho, thank you very much for the explanation; I understand a bit more about this repo.

So to provide a better support for vi editing mode, one could

  1. incrementally change/add bindings to `share/functions/fish_vi_key_bindings.fish` and, if needed, write some other function in `src/reader.cpp` to support these new bindings,
  2. or what you suggest.

The second approach looks like a monumental change, to me, and it'd probably need some nowledge of the fish syntax.

The first approach would probably be more doable, as it would just require, on the fish side, changing `bind -s --preset dw kill-word` to `bind -s --preset dw kill-word-and-also-the-space-after-it`, with `kill_word_and_bla` being a new `case` in the implementation of `reader_data_t::handle_readline_command`.

Needless say that approach 2 is the one I'd like to see done, even though for now I have little clue where to start. But approach two could at least fix some really annoying but simple issues, like <kbd>d</kbd><kbd>e</kbd> and <kbd>d</kbd><kbd>w</kbd> having, erroneously, the same implementation.

Any thoughts?

**Comment by faho** [comment]
>The first approach would probably be more doable, as it would just require, on the fish side, changing bind -s --preset dw kill-word to bind -s --preset dw kill-word-and-also-the-space-after-it

Doing `dw` is easy, but what about `d2w` and `d2tm`?

That's the "motion" part this is about, and that's basically unworkable with your first approach.

**Comment by Aster89** [comment]
Well, fish doesn't handle those anyway, at the moment...

However, as I wrote, I totally agree this approach is trash with respect to the one you suggested, but the vi-mode that fish supports at the moment is simply unusable.

I'll try to find some time to explore the code a bit more.

**Comment by Aster89** [comment]
@faho , I had some time to explore the code a bit more. I've `grep`ed all `*.fish` files in the repo for `forward-word`, and I see it's used also in `share/functions/fish_default_key_bindings.fish`, `share/functions/__fish_shared_key_bindings.fish`, and `share/functions/nextd-or-forward-word.fish`. If add to this the fact that the _kill_ = delete terminology is used, I suspect that all these functions in `src/reader.cpp` (`forward_word` and many others) are shared between vi-mode and emacs-mode.

Is this the case?

**Comment by faho** [comment]
It is shared, yes.

**Comment by umanwizard** [comment]
I tried working on getting a working vi mode for fish. I didn't get it into a mergeable state, and it ended up being _a lot_ of code, but it already works much, much better than before.

In case anyone wants to pick up where I left off, or finds it useful: https://github.com/umanwizard/fish-shell/tree/fix_vi

**Comment by umanwizard** [comment]
The key insight is that vi motions are a language with a grammar. They cannot be supported simply by mapping various actions to various strings.

E.g., instead of mapping `dw` to "delete word", `d2w` to "delete two words", and so on ad infinitum, what you really need to do is map `d` to "set current action to 'delete'", map `2` to "start parsing action count", and "w" to "perform current action with current count" ; and so on.

Then most things will compose correctly, but there are still some edge cases (like `cw` is actually equivalent to `ce`).

Also, the word boundary detecting code is completely wrong and needs to be rewritten, even for emacs. That's about where I got frustrated, gave up, and switched back to zsh.

**Comment by Aster89** [comment]
@umanwizard , I've given a look at your change and I see it is huge. However, rebasing it to the latest commit only generates 3 conflicts, which seems good; on the other hand, I would still have absolutely no clue of how to handle those conflicts, let alone the fact that I'd need sometime to understand how the existing code works, in order to be able to start putting my hands on it.

Would you be able to give a look at that, just in case those conflicts look easily solvable to you?

However, you wrote you _didn't get it into a mergeable state [...] but it already works much, much better than before_; what you mean by that?

**Comment by Aster89** [comment]
@umanwizard, I have rebased your changes on the latest commit of the master branch. Here's the result 8220a09. I haven't squashed the commits for now so I can have them as a reference while I try to understand how I can continue this change.

Since <kbd>c</kbd> seems to work as expected, I think I've correctly handled the rebase's conficts.

**Comment by umanwizard** [comment]
Please check with @faho or one of the other project maintainers that this is actually the desired approach, so you don’t waste time working on something that won’t be merged.

**Comment by ridiculousfish** [comment]
I took a look at the commits and it's looking great. We'd be thrilled to merge when they're ready.

**Comment by braham-snyder** [comment]
If anyone wants to hook fish up to vim itself, [athame](https://github.com/ardagnir/athame) has good tests, and it already connects to zsh (which doesn't use readline either).

Its FAQ says:

> If you have a shell that I'm missing, you can try making a patch to communicate between it and Athame (see athame_readline.h and athame_zsh.h for the functions you need to implement).

Unfortunately I'm terrible at C myself. Just to ping a couple people from a ways back in the thread too, in case they've unsubbed but this interests them: @mqudsi @ahillio 

&nbsp;

That said, any kinds of vi mode improvements, like @umanwizard's and any extensions of it, would of course be awesome. Excited for the improvements already in 3.2, too.

**Comment by MonAaraj** [comment]
I know, I'm probably very late, and it's probably just to provide a non-needed suggestion, but, has anyone here thought about maybe using or modifying a sort of Vim keybind handler? Would, maybe, something like [Zep](https://github.com/Rezonality/zep/) could help, or something like some of [libvim](https://github.com/onivim/libvim)'s implementation? I feel at this point there has got to be some software that would make it easy for developers to start programming it, but I'm not really quite sure. I'm very sorry if this comment wasn't of use, though.

**Comment by MonAaraj** [comment]
I completely agree. Athame looks very interesting, and it looks very promising for fish, I'm just not quite sure if it does work on fish. Though, it does work on ZSH which does also have it's own readline, but Athame doesn't seem to mention it. I feel this could be done without much difficulty if maybe some people made a PR to allow fish comptability and put it in the README.md, but I'm not quite sure, neither.

**Comment by ahillio** [comment]
Regarding my last comment/inquiry about the scope ("fix various vi-mode issues" vs "implement robust vi-mode" ?) and status (ready to merge?)... I'd love to hear the perspective of a maintainer on this... in case @faho or @ridiculousfish or someone would like to chime in on it :)

**Comment by faho** [comment]
I'm not entirely sure what you want.

If someone opens a PR with something that improves the situation, we can merge it. I don't see the point in asking things to be perfect, but I'm also not going to chase any particular implementor and hound them to do anything.

As I don't use vi-mode (I don't see the point in it in a shell context) I'm going to have to defer to other people on fixing it.

**Comment by ahillio** [comment]
@faho thanks for quick response... more specifically I was wondering....

Would it be worthwhile opening a pull request for https://github.com/fish-shell/fish-shell/commit/8220a0932e86963cd0f8c255d0e0a52d68c450dd?

What do you think about the possibility of instead using libvim/athame/neovim for achieving a robust vi-mode?  I understand GNU Readline is out of the question.  But would you recommend utilizing a different external library that could be leveraged for more functionality instead a piecemeal approach?

**Comment by faho** [comment]
>What do you think about the possibility of instead using libvim/athame/neovim for achieving a robust vi-mode?

Non-starter. We don't want to add dependencies, especially not for secondary functionality like vi-mode (as it's not even used by most users).

No external libraries for this, no.

**Comment by ahillio** [comment]
Gotcha, thanks!

**Comment by faho** [comment]
To be clear: I'm not saying that it'll definitely be merged, the code will have to be acceptable and it will have to actually improve things in some way and not make them worse in others.

**Comment by ridiculousfish** [comment]
I would be comfortable taking a dependency for vi mode, as none of the current contributors seem to have much appetite for working on it. Something like libvim is probably too heavyweight (it parses VimScript, etc), but I've considered experimenting with forking and incorporating zsh's vi-mode.

**Comment by faho** [comment]
>I would be comfortable taking a dependency for vi mode

Wait, do you mean "copy a few source files into our tree" like we did for math? That would be acceptable.

But adding a proper dependency that all users must install I consider to be waaaayyy too much for a minority use case, and I would want to reject any PR that adds it (before anyone goes off working on one).

**Comment by MonAaraj** [comment]
> Something like libvim is probably too heavyweight (it parses VimScript, etc)

I agree, that's why I suggested modifying, or in our case, only taking in a certain part of the files, specifically the ones that handle some keybinds. Since that seemed to be acceptable, and libvim itself is supposed to have very little dependencies in the first place, I believe we could use *a part* of it (or [Zep](https://github.com/Rezonality/zep/)), to get the job done.

**Comment by OJFord** [comment]
Can I suggest (as doing it properly is hard, a dependency is undesirable) that although @umanwizard is absolutely right that 'you can't just map `dw` to delete word, `d2w` to two, etc. ad infinitum'... you can 'just map' some small number of them, and get a hell of a way up the [Pareto curve](https://en.wikipedia.org/wiki/Pareto_distribution).

Honestly just `c2w` & `c3w` would get me past ~95% of my 'gah why do I always forget this doesn't work' moments.

(It's particularly frustrating because it's not just 'doesn't work', it's 'behaves as `2w`', so the fix isn't just `dw cw` or something, it's `b dw cw`, or `e v b b c`.)

Also, regarding:
> (Also in the meantime does anybody have a good workaround for deleting long arguments?)

because it doesn't seem to have been answered (sorry if I missed it) - I use visual mode, so `d5w` becomes `vwwwwwd`.. not great, but better than `dwdwdwdwdw`, and often if it's that long you can do say `v$b` instead.

**Comment by ahillio** [comment]
Even if "Robust Vi-Mode" was a plugin (due to extra dependencies), and not part of Fish core, that would be awesome I think.  If vi-mode is too small minority, perhaps that would make more sense?

**Comment by faho** [comment]
@ahillio That doesn't solve the problem, which is that someone needs to write it. It also introduces an additional problem, which is that someone needs to write the interface.

**Comment by NeilGirdhar** [comment]
Instead of trying to slowly cobble together a vim interpreter, can you work with the neovim people to have a persistent lightweight neovim process open that processes commands?  The big advantage to that is that it would inherit the neovim configuration, syntax highlighting, etc.

**Comment by kittydoor** [comment]
Considering the new rewrite to Rust (crustaceans unite!), would a patch for implementing this within the source code of the shell (as opposed to the fish function in share) be a good approach?

I don't know if my Rust knowledge will be enough, nor have I taken a good in depth look at the internals of fish but I would love to consider switching to it from ZSH finally, and working on this sounds like a fun project to make it work a lot better for myself any many others :)

**Comment by tesuji** [comment]
This is fixed in the latest fish version.

**Comment by OJFord** [comment]
Is there something we need to do to enable it? I have `fish, version 4.2.1`, but I'm still seeing the same behaviour as described above.

**Comment by krobelus** [comment]
@OJFord I don't know exactly what you're missing exactly but the upcoming https://github.com/fish-shell/fish-shell/pull/12170 adds support for counts for all these operators; without count it should already work. Better open a new issue if needed

**Comment by OJFord** [comment]
@krobelus Oh, ok, I was just going from 'fixed in the latest version' and in the 4.2 milestone above, assumed that meant it had shipped but didn't see it in 4.2.1 or subsequently 4.3.
