### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by ShalokShalom** [fish-shell/fish-shell#4116]
1) There is one part of the documentation which offers infos to functions, while that one is not in the index, which becomes even more confusing once you like to link this section and when you see the actually indexed function section, which explains the same thing in a different manner. In fact, there is even a third section, which explains the function syntax.
http://funkyimg.com/i/2u7uo.png
http://funkyimg.com/i/2u7uZ.png
http://funkyimg.com/i/2u7v1.png

2) Functions seems to need an `; end`
This is nowhere written in the not indexed section of the functions and also not yet in the example in this section: http://fishshell.com/docs/current/tutorial.html#tut_functions

3) There is no description about the `and` replacement of &&. In fact, && is not mentioned a single time on the whole wiki as far as ctrl+f can find and the error message in fish itself is even more confusing:

> Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.

Why not: 
> Unsupported use of '&&'. In fish, please use `and` instead?

4) Universal functions do not work for me at all, as described.

**Comment by faho** [comment]
>Functions seems to need an ; end

Well, no. They need an `end` as a separate statement. When you put that on another line, you don't need the semicolon. When you put it on the same line, you do.

I.e. it is

```fish
function name
     some code
end

or

function name; some code; end
```

This is something we might want to make clearer in the tutorial - maybe a section on it.

>There is no description about the and replacement of &&. In fact, && is not mentioned a single time on the whole wiki as far as ctrl+f can find

Huh... I would have sworn it was in there. We should probably add it. Where would you expect it?

>Why not:

>    Unsupported use of '&&'. In fish, please use and instead?


Because then people would write something like `grep -q something somefile and echo something`. In that case, `grep` would interpret the `and echo something` as three more arguments (i.e. as three more files to scan). I _have actually seen this happen_, with the current error message.

Like the `end` above, the `and` needs to be a separate statement, so you can either put it on another line or if you do put it on the same line you need a semicolon. I.e.

```fish
grep -q something somefile; and echo something

# or

grep -q something somefile
and echo something
```

>Universal functions do not work for me at all, as described.

Sorry, where have you described that? What do you mean by "universal functions"?

**Comment by ShalokShalom** [comment]
I think in general, that an update of the current examples (which includes the ; end stuff) plus the integration of the currently not indexed section into the already indexed one can help. There is even a fourth section with a little bit info about functions by the way: http://fishshell.com/docs/current/index.html#identifiers

And I think a link from the function section to the function section in the command section is also nice. 
Here is to mention, that this one actually start here: http://fishshell.com/docs/current/commands.html#funced

While I think it's easier to start with `function` itself, which seems impossible since the command section is sorted by alphabet, rather than workflow.

I call universal functions, what your documentation calls universal functions: 
http://fishshell.com/docs/current/tutorial.html#tut_universal

**Comment by faho** [comment]
Note that there is a mention of "&&" in the tutorial - file:///usr/share/doc/fish/tutorial.html#tut_combiners:

>Unlike other shells, fish does not have special syntax like && or || to combine commands. Instead it has commands and, or, and not.

We should probably add a multi-line example there, and add a section on "separating commands (semicolons)" (or something like that).

>And I think a link from the function section to the function section in the command section is also nice.

Yes.

>While I think it's easier to start with function itself, which seems impossible since the command section is sorted by alphabet, rather than workflow.

The "command" section is meant as a reference for a certain command. It is the same content that is available via man pages and via the "--help" output of the command (`man function` or `function --help` will give you the same as `help function` in slightly worse formatting).

For that, it seems nicer to have it alphabetically.

>I call universal functions, what your documentation calls universal functions:

Please read that section again. It does not talk about "universal functions", it talks about "universal **variables**". So my question is: What did you try, and how did it not work?

**Comment by ShalokShalom** [comment]
Ah yeah, my bad, that thing about universal variables. I miss read that, apologies. :)

About the && section: I find it useful, when it appears in the docu as well, not just the tutorial.

**Comment by faho** [comment]
@ShalokShalom: Please see the two commits I just pushed. I hope they help to clarify the tutorial a bit.

>About the && section: I find it useful, when it appears in the docu as well, not just the tutorial.

Honestly, I'm not quite sure where the division between "the documentation" and "the tutorial" should be.

**Comment by ShalokShalom** [comment]
Hit the documentation button on the homepage and try to find &&

I still dont get how `Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.` can help and think that 

> Unsupported use of '&&'. In fish, please use `; and`.

is a proper alternative.

**Comment by faho** [comment]
>Hit the documentation button on the homepage and try to find &&

Oh, sorry! Of course it should be easy to find something on "&&". What I was trying to say was that I wasn't sure how "the documentation" (i.e. index.html) and "the tutorial" (i.e. tutorial.html) should be separated - should we link from one to the other? Should everything be mentioned in both?

>I still dont get how Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'. can help 

What is probably confusing you here is the "COMMAND". That's a placeholder for the actual command. So if you try to execute

```sh
grep -q something somefile && echo "Found"
```

and fish prints that error, what it means is that you should execute

```fish
grep -q something somefile; and echo "Found"
```

i.e. the first "COMMAND" is `grep -q something somefile` and the second is `echo "Found"`.

>and think that

>    Unsupported use of '&&'. In fish, please use ; and.

>is a proper alternative.

With the semicolon, this is actually a bit better (since an additional semicolon doesn't hurt).

I'll check our issues to see how other people have misunderstood this.

**Comment by krader1961** [comment]
Is there something to be done here (e.g., converted to an "enhancemen" issue) or should this be closed as answered?

**Comment by ShalokShalom** [comment]
IMHO, implement && support or at least a sane error message. 
I got a lot of issues with fish yet within one week of usage, since some things are unsupported and all the scripts are in bash, without mentioning that (in the Internet.)

So i copy and paste and get strange errors, which i dont, if i use bash. So lets tackle an own issue, meaning "drop-in-replacement" functionality?
