### ISSUE TITLE
Autocomplete with Tab Error 

### ISSUE THREAD

**Issue by trmml** [fish-shell/fish-shell#4302]
While using autocomplete with tabs (specifically with node, it seems), I'm repetitively getting this error.

```
__fish_not_contains_opt: Unknown option --version
__fish_not_contains_opt: Unknown option --version
__fish_not_contains_opt: Unknown option --version
__fish_not_contains_opt: Unknown option --eval
```

This problem doesn't occur when autocompleting with the right arrow key, only tab.

I'm currently running version 2.6.0 (latest version.) `uname -a` spits out `Darwin Joshs-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`, and running fish without third-party customizations makes no difference and does not affect the problem I'm having.

I uploaded an [asciinema video](https://asciinema.org/a/fg6aybMouHw96vIYxhAYWkovq) to show this problem. The first autocomplete was done using the right arrow key and the second was done using tabs.

No idea what the problem is, but I restored my machine only a few days ago and have only installed a few things since, so I'm not sure what the problem could be caused by 😛

**Comment by krader1961** [comment]
You're using a version of fish that has a broken `node` completion script. This was fixed by commit a0c8a9e8e on 2017-06-09 which will be part of the 2.7.0 release. You can fix the problem by installing just the [updated completion script](https://github.com/fish-shell/fish-shell/blob/master/share/completions/node.fish).

**Comment by trmml** [comment]
I ran the updated completion script (`fish node.fish`), didn't seem to fix the problem (even after a reboot). No worries though, I can wait for the 2.7.0 release. Thanks 👍

**Comment by krader1961** [comment]
> I ran the updated completion script (`fish node.fish`),

That's not how completion scripts work. You need to put the fixed version in `$__fish_datadir/completions/` or `~/.config/fish/completions/`. It will be autoloaded when you try to complete the node command.

**Comment by trmml** [comment]
I'm not very familiar with completion scripts, so my apologies for the misunderstandings. I saved `node.fish` to `$__fish_datadir/completions/` and restarted my Terminal and I still seem to be getting the error.

**Comment by krader1961** [comment]
If you run `grep __fish_not_contain_opt $__fish_datadir/completions/node.fish` you should see these lines:

```
complete -x -c node -s v -n '__fish_not_contain_opt -s p -s i -s e eval print interactive' -l version --description "Print node's version"
complete -c node -n '__fish_not_contain_opt -s v -s p -s i version print interactive' -r -s e -l eval --description 'Evaluate script'
complete -c node -n '__fish_not_contain_opt -s v -s e -s i version eval interactive' -r -s p -l print --description 'Print result of --eval'
complete -c node -n '__fish_not_contain_opt -s v -s p -s e version print eval' -s i -l interactive --description 'Always enter the REPL even if stdin does not appear to be a terminal'
```

Note the lack of `--` before the long options; i.e., it says `version` not `--version`.

It's possible you've got the broken version in some other directory. Check if it appears in any of the directories printed by `echo $fish_complete_path` other than `$__fish_datadir/completions/`.

**Comment by trmml** [comment]
That's so weird, I've checked all the locations of other directories with `echo $fish_complete_path`, as well as scoured my hard drive for other `node.fish` with `find / -type f -name "node.fish"`– the only path for it is `/usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish`, which is the updated completion script you linked me to.

**Comment by faho** [comment]
@trmml: Can you try `grep '__fish_not_contain_opt' $fish_complete_path/*.fish`?

**Comment by trmml** [comment]
@faho: I get this as a result:

```
/usr/local/Cellar/fish/2.6.0/share/fish/completions/git.fish:complete -f -c git -n '__fish_git_using_command tag; and __fish_not_contain_opt -s d; and __fish_not_contain_opt -s v; and test (count (commandline -opc | string match -r -v \'^-\')) -eq 3' -a '(__fish_git_branches)' -d 'Branch'
/usr/local/Cellar/fish/2.6.0/share/fish/completions/logkeys.fish:complete -c logkeys -s m -l keymap -n '__fish_not_contain_opt -s u' -d 'Use file as input KEYMAP'
/usr/local/Cellar/fish/2.6.0/share/fish/completions/logkeys.fish:complete -c logkeys -s u -l us-keymap -n '__fish_not_contain_opt -s m' -d 'Treat keyboard as standard US keyboard'
/usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish:complete -x -c node -s v -n '__fish_not_contain_opt -s p -s i -s e --eval --print --interactive' -l version --description "Print node's version"
/usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish:complete -c node -n '__fish_not_contain_opt -s v -s p -s i --version --print --interactive' -r -s e -l eval --description 'Evaluate script'
/usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish:complete -c node -n '__fish_not_contain_opt -s v -s e -s i --version --eval --interactive' -r -s p -l print --description 'Print result of --eval'
/usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish:complete -c node -n '__fish_not_contain_opt -s v -s p -s e --version --print --eval' -s i -l interactive --description 'Always enter the REPL even if stdin does not appear to be a terminal'
/usr/local/Cellar/fish/2.6.0/share/fish/completions/systemd-nspawn.fish:complete -c systemd-nspawn -n "__fish_not_contain_opt -s b boot" -a "(__fish_complete_subcommand)" -f
```

**Comment by krader1961** [comment]
> /usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish:complete -c node -n '__fish_not_contain_opt -s v -s p -s i --version --print --interactive' -r -s e -l eval --description 'Evaluate script'

That is the broken completion script. It's why you're getting those errors.

> ... which is the updated completion script you linked me to.

Not according to the `grep` output.

**Comment by trmml** [comment]
I just tried moving into `/usr/local/Cellar/fish/2.6.0/share/fish/completions/node.fish` and `wget`ing the updated completion script you linked me to from there, which seems to have fixed it.

It's possible previously the script wasn't being saved to the completions directory? Sorry for the confusion, my bad! Thanks again for the help 👍
