### ISSUE TITLE
Command substitutions randomly truncate large output

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5611]
This is a regression since 3.0.0. It is not in Integration_3.0.1.

Running

```fish
for i in (seq 1 10000)
    echo $i
end
```

sometimes randomly stops before printing "10000". In particular it seems to like "5956".

@ridiculousfish: This bisects to 9a4153f5e2f0a0ea74f395248f5dbd40b55e8dc8.

**Comment by ridiculousfish** [comment]
Nice find. Easier repro is `count (seq 1 10000)`

**Comment by zanchey** [comment]
> Easier repro is `count (seq 1 10000)`

That would make a good test, perhaps.

**Comment by ridiculousfish** [comment]
Fixed with added tests in 6f682c84052a8bd52f14122a36e878037cbb868e

**Comment by faho** [comment]
Okay, this still happens on OpenIndiana/Illumos/Solaris/SunOS.

**Comment by ridiculousfish** [comment]
Hmm, which is easiest to test on?

**Comment by faho** [comment]
That's what I've been testing on (that word salad is a bit facetious - I'd love it if they could drop one or two of their names, because they still appear all over the place).

Good news is that it's apparently the last test failure.

**Comment by floam** [comment]
`_REENTRANT` probably

**Comment by ridiculousfish** [comment]
note you'll have to re-run cmake to pick this up

**Comment by faho** [comment]
I can confirm that the operating system formerly known as Solaris now seems to pick up all input.

**Comment by zanchey** [comment]
I suspect this was further fallout from a lack of anything analogous to AC_USE_SYSTEM_EXTENSIONS in CMake.

**Comment by floam** [comment]
So that did quite a bit:


```

**Comment by floam** [comment]
It seems like we may want to be doing `__EXTENSIONS__`, `_ALL_SOURCE`, `_DARWIN_C_SOURCE`, `_GNU_SOURCE`, `_POSIX_PTHREAD_SEMANTICS` at least.

**Comment by floam** [comment]
> but I think using C++ they shouldn't do anything?

It seems that `__STDC_WANT_LIB_EXT2__` can make these available in string.h:

* `fmemopen`
* `open_memstream`
* `vasprintf`
* `asprintf`
* `getdelim`
* `getline`
* `strdup`
* `strndup`
* `open_wmemstream`
