### ISSUE TITLE
cd completion spews on receiving [

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#562]
> cd /tmp/[<tab>

    Tokenizer error: 'Unexpected end of string, parenthesis do not match'
    /usr/local/share/fish/functions/__fish_complete_cd.fish (line 7): begin; printf \%s\n /tmp/[*/ ;end eval2_inner <&3 3<&-"

**Comment by smarek** [comment]
Could you please move this bug upper on priority ladder? It's already 3 years old and number of duplicates closed is growing. AFAICT in 2.2.0 this is still not fixed, am I right?

**Comment by ridiculousfish** [comment]
This may have been fixed by 0a99772572ab8632f103f05570da707683980d17, I can't reproduce it any more. @faho do you think there's anything left to do here?

**Comment by smarek** [comment]
I have installed 2.2.0 from Homebrew (OSX) and I can still reproduce that, should I go with HEAD version?

**Comment by faho** [comment]
It doesn't spew that error anymore and handles mostly okay - the issue happens when you enter "[" manually.

If you have a directory called "[foobar]", enter "[foo" and then complete, it will complete to "[foobar\]", which is actually a valid way to express that directory name. If you have a directory name without the closing bracket, it won't escape anything if you've manually entered it (picking via pager is okay).

Do we have a bug about that? It's kinda the same thing as #2300 - our completion doesn't always escape properly.

>should I go with HEAD version?

@smarek: I'm biased and I'm saying yes. It's improved at least.

**Comment by smarek** [comment]
In my case, i'm talking about directories with `&` (ampersand) in name, I've reported this back in 2015 in #2242

**Comment by faho** [comment]
That case works now,

**Comment by zanchey** [comment]
Sounds like this is solved - hooray!

**Comment by krader1961** [comment]
I can't reproduce any of the problems reported here so I'm closing this so we've got a better idea of what's left to complete for the 2.3.0 release.
