### ISSUE TITLE
Fish causing errors in terminal in ArchLinux with systemd >=241.0

### ISSUE THREAD

**Issue by f0ff886f** [fish-shell/fish-shell#5689]
`fish, version 3.0.1`, `ArchLinux`, `ssh`, `$TERM = linux`

When installing `systemd >= 241.0` in ArchLinux it now has the following version string:

`$systemd_version = 241 (241.7-2-arch)`

When using tab completion (or sometimes just on the first command after a systemd upgrade, the following error would get printed (all text after `systemctl daemon-reload`):

```
root@bank ~# systemctl daemon-reload    Integer 241 in '241 (241.7-2-arch)' followed by non-digit
        Integer 241 in '241 (241.7-2-arch)' followed by non-digit
```

Seems to repro only on Fish.

Discussion on Arch forums: https://bbs.archlinux.org/viewtopic.php?pid=1833187

**Comment by faho** [comment]
Yup, our version extraction was a bit naive. Fixed.

**Comment by f0ff886f** [comment]
Thank you!

**Comment by alxpettit** [comment]
Here's a hotfix for this issue, since this commit is taking a long time to get pushed to release:

https://gist.github.com/alxpettit/63b9f157e4c0b688b444d1cd02874be8

**Comment by nerddan** [comment]
> Yup, our version extraction was a bit naive. Fixed.

Is it fixed? I am still getting this issue.
```
$ fish -v
fish, version 3.0.2
$ systemctl da Integer 242 in '242 (242.29-1-arch)' followed by non-digit
Integer 242 in '242 (242.29-1-arch)' followed by non-digit
e                       mon-re
```

**Comment by nerddan** [comment]
Am I supposed to wait until fish get updated in Arch repository?

**Comment by limadm** [comment]
Yes, this issue was fixed in 3.0.3 #5772, should come to arch repo soon (https://www.archlinux.org/packages/community/x86_64/fish/).
You can also install fish-git from AUR or directly from sources.

**Comment by f0ff886f** [comment]
Just an FYI for anyone who read @limadm's comment, 3.0.3 still didn't release and the best hotfix is @alxpettit's response above.

**Comment by eoli3n** [comment]
Affects NixOS, 3.0.3 still not released.
The hotfix can't be played has is on NixOS.

**Comment by NotAFile** [comment]
It seems the 3.0.3 release was cancelled, with plans to release 3.1.0 instead, which seems to be taking longer than expected. Since this is now affecting stable releases of fedora as well, perhaps a 3.0.3 could be reconsidered?

**Comment by AlexWayfer** [comment]
> It seems the 3.0.3 release was cancelled, with plans to release 3.1.0 instead, which seems to be taking longer than expected. Since this is now affecting stable releases of fedora as well, perhaps a 3.0.3 could be reconsidered?

https://github.com/fish-shell/fish-shell/issues/5934#issuecomment-570934276

> **faho** commented 5 days ago
>
> "When it's done"

**Comment by NotAFile** [comment]
Right, if only the release notes are the blocker, 3.0.3 release would be very silly.

I know the issue too well from my own projects :sweat_smile:.

**Comment by kylesferrazza** [comment]
@eoli3n if you are using home-manager, this is the solution I am using on NixOS until 3.1.0 comes out:

https://github.com/kylesferrazza/nix/blob/master/programs/shells.nix#L54-L58

**Comment by gebner** [comment]
@kylesferrazza @NotAFile @AlexWayfer @eoli3n Please submit nixos bugs (also) to the nixos bugtracker.  The fix is already in the unstable and release channels: https://github.com/NixOS/nixpkgs/pull/77951
