### ISSUE TITLE
Cannot call help in WSL 

### ISSUE THREAD

**Issue by edyu** [fish-shell/fish-shell#6338]
fish, version 2.7.1
Linux strongwin 4.19.79-microsoft-standard #1 SMP Mon Oct 14 00:50:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

When I run **help** in the terminal in WSL (Windows Subsystem for Linux), I get the following error:

```
 $ help                                         
Start : This command cannot be run due to the error: The system      
cannot find the file specified.
At line:1 char:1
+ Start "file:///usr/share/doc/fish/index.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process],     InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

**Comment by zanchey** [comment]
That looks like a PowerShell error to me, which is not something I'd expect to see under WSL. What does `type start` show?

**Comment by faho** [comment]
>fish, version 2.7.1

@edyu If possible you'll want to upgrade to 3.0.2, which had changes in `help` specifically for WSL (99ecaec17501542b3627f531fc8570d467319bbf)

Use [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) to do so.

**Comment by ohk2kt3t4** [comment]
I am getting the same error with fish 3.0.2 on WSL1 using the Ubuntu package. fish finds `www-browser` which is symlinked to [wslview](https://github.com/wslutilities/wslu/wiki/wslview), which is "a fake WSL browser that can help you open link in default Windows browser." The URL being supplied to www-browser in this case is not a Windows path, so the OS cannot open the file. By using the same fix as in #6358 this problem is fixed for me.

Now just have to rethink the logic in `help.fish` to detect this case and workaround it. Continue discussion in #6358.

**Comment by edyu** [comment]
Same problem on fish 3.0.2
<pre>
 ~ fish --version                                                                                                      
fish, version 3.0.2                                                                                                    
 ~ help                                                                                                                
Start : This command cannot be run due to the error: The system cannot find the file specified.                        At line:1 char:1                                                                                                       
+ Start "file:///usr/share/doc/fish/index.html"                                                                        
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                            + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException                             + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand            
</pre>

**Comment by zanchey** [comment]
Fixed by #6358.

**Comment by graphixillusion** [comment]
I'm still receiving the same error described in the first post. I tried version 3.1.0 under WSL2, Win 10 2004. Meanwhile, under Windows 19 1909 and MSYS, this what i got: 
```
MSYS_NT-10.0-18363 VM-PC 3.0.7-338.x86_64 x86_64
 /  fish --version                                     Sat Apr 11 23:41:10 2020
fish, version 3.1.0
 /  help                                               Sat Apr 11 23:41:15 2020
Microsoft Windows [Versione 10.0.18363.752]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\msys64>

```
As you can see, when i type "help" it simply displays the current Windows version and then exit the fish shell.

**Comment by krobelus** [comment]
sounds like a different problem; can you show the output of `fish_trace=1 help`?

**Comment by graphixillusion** [comment]
@krobelus this is the log under MSYS. It's pretty long so i attach a txt file.
[log.txt](https://github.com/fish-shell/fish-shell/files/4466649/log.txt)

**Comment by krobelus** [comment]
@graphixillusion the last command in that log is
```fish
/c/Windows/System32/cmd.exe /c 'start file:///usr/share/doc/fish/index.html'
```

On a WSL system here this ony works if `index.html` is accessible to the Windows host, for example if it is on `/mnt/c` instead of `/usr/share`. In fact, `wslpath` fails if it is not accessible, then we fall back to the online version at fishshell.com.
Since you don't have wslpath, is there some other way to convert the path? Or can we detect MSYS somehow and then always fall back to the online version.

**Comment by graphixillusion** [comment]
@krobelus this log is not from the wsl, i have run it under MSYS.

**Comment by MathWhiz** [comment]
On WSL2, files can be accessed in the windows system under `\\wsl$\[distro name]`, so if wsl is detected, the program could open e.g. `file://///wsl$/Ubuntu-20.04/usr/share/doc/fish/index.html`

**Comment by malobre** [comment]
> 
> 
> @krobelus this log is not from the wsl, i have run it under MSYS.

This is another problem, check https://github.com/fish-shell/fish-shell/issues/7113
