### ISSUE TITLE
fish 3.1.0: __z --list | fzy results in tcsetattr error

### ISSUE THREAD

**Issue by benmkw** [fish-shell/fish-shell#6624]
fish --version 3.1.0 (now reverted to 3.0.2)

macos 10.14.6
 `echo $TERM` xterm-256color, using normal mac terminal, but happens the same in others

first reported against z https://github.com/jethrokuan/z/issues/86
The reason for why this was an issue for me is I'm using `alias z="cd (__z -l 2>&1 | fzy | sed 's/^[0-9,.]* *//')"` (maybe there is a better way)

behaviour changed from 3.0.2 to 3.1.0:
in short: `__z --list | fzf` results in `Failed to read /dev/tty` while `ls | fzf` works fine, `__z --list | rg llvm` works fine as well 

fzf and fzy show nearly the same behaviour/ only difference is that the output of fzy is `tcsetattr: Input/output error` and fzf is `Failed to read /dev/tty`

the behaviour seems to be timing sensitive, it fails most of the time though

I suspect this commit might have changed the behaviour 
https://github.com/fish-shell/fish-shell/commit/2a3677b38659835858c9d557e7d920630bfbcbb8

**Comment by yujinyuz** [comment]
@benmkw how did you revert back to 3.0.2?

**Comment by faho** [comment]
>I suspect this commit might have changed the behaviour

Pretty sure that's not it, as it only affects fish's startup.

I think the issue is in our general job cleanup - there's always some weird edge case. Here it's a function (`__z`) that pipes to a command (`fzy`) that then both accesses the terminal and pipes to another command (`sed`).

**Comment by ridiculousfish** [comment]
In the case of `function | command`, the pgroup should be fish itself; however if `fzy` changes its pgroup and accesses the terminal then it will have issues. I'll track this down.

**Comment by zanchey** [comment]
I'm going to try and get 3.1.1 out shortly, but if this is a relatively easy fix I would be happy to make a 3.1.2.

**Comment by ridiculousfish** [comment]
Bisects to 3bbee06248b073fc30ae5cc8e418c943c8cd6e11

**Comment by ridiculousfish** [comment]
The problem is that we aren't propagating the proper pgid into command substitutions. fish launches fzf, gives it control of the terminal, then runs a function which contains a command substitution; fish then gives a job in the cmdsub control of the terminal. fzf then gets SIGTTIN when it tries to manipulate the tty.

This existed in fish 3.0, but the bug is exposed in 3.1 because fish no longer buffers the `__z` output.

**Comment by krobelus** [comment]
Sounds similar to #6300

**Comment by ridiculousfish** [comment]
As a workaround you can wrap `fzf` in a function or block, e.g.:

    function fzf; command fzf $argv; end

**Comment by benmkw** [comment]
> As a workaround you can wrap fzf in a function or block, e.g.:

I can confirm this fixes my problem for the moment, thanks!

_I'll leave the issue open but feel free to close it depending on your workflow_

**Comment by krobelus** [comment]
Does anyone have a way to reproduce this reliably? I occasionally got the `tcsetattr` errors when running `echo (__z --list | fzy)` but not anymore. Probably the `__z` function can be reduced.

**Comment by cjappl** [comment]
@krobelus I think this is the same issue, this is 100% reproducible 

`eval "git log" | env FZF_DEFAULT_OPTS="" fzf`

**Comment by ridiculousfish** [comment]
I merged this into 3.1.1 as 2d3c914a9db01a2646abf2fbd8a42d5025fde198

**Comment by cjappl** [comment]
I just checked 3.1.1 and this example is still broken with the `Failed to read /dev/tty` error

`eval "git log" | env FZF_DEFAULT_OPTS="" fzf`

Let me know if I should open a separate issue for this

**Comment by faho** [comment]
@cjappl Please double-check you're actually running 3.1.1 by restarting fish. I just tested it before, reproduced the issue, upgraded and could no longer reproduce.

**Comment by cjappl** [comment]
@faho definitely! Good to double check, it appears that I am running the right version:

```
$ fish --version                                                                                                                                                                                    
fish, version 3.1.1
$ eval "git log" | env FZF_DEFAULT_OPTS="" fzf                                                                                                                                                      10:16:48
Failed to read /dev/tty

**Comment by faho** [comment]
Please `echo $version` and then test it.

`fish --version` will print the version of any *new* fish, $version contains the version of the *current* fish.

Also which OS is this on?

**Comment by cjappl** [comment]
``` 
[I]|cjappl@CJAPPL-MBP:~/D/C/p/c/forgit|master✓
$ echo $version                                                                                                                                                                                     11:11:02
3.1.1
[I]|cjappl@CJAPPL-MBP:~/D/C/p/c/forgit|master✓
$ eval "git log" | env FZF_DEFAULT_OPTS="" fzf                                                                                                                                                      11:11:05
Failed to read /dev/tty
```

OSX Mojave

**Comment by ridiculousfish** [comment]
I am unable reproduce on Mojave with fish 3.1.1 or 3.1.2 - `eval "git log" | env FZF_DEFAULT_OPTS="" fzf` works and does not output an error message.

@cjappl any more clues to reproduce? What terminal are you using, what does `fzf --version` show, what is `type fzf`, etc?

**Comment by cjappl** [comment]
Here's the info on the things I'm running on now:
```
fish $version    3.1.2
fzf --version    0.21.1 (brew)
type fzf            fzf is /usr/local/opt/fzf/bin/fzf

```
I'm finding it behaves differently in different circumstances.

Inside of tmux, in a git repository 
- 'Failed to read /dev/tty', the original issue I was mentioning

Inside of tmux, outside of a git repository
- behaves as expected, fzf is fed nothing, and runs until quit

Outside of tmux, in a git repo
- `eval "git log" | env FZF_DEFAULT_OPTS="" fzf`
    - seems to hang indefinitely
- `git log | env FZF_DEFAULT_OPTS="" fzf` 
    - works as intended, feeding each line of git log to fzf

**Comment by ridiculousfish** [comment]
Unfortunately I still can't reproduce. When this hangs, is any particular process using a lot of CPU (or memory)? Can you get a sample of it?

**Comment by cjappl** [comment]
It doesn't appear to be ramping up any serious memory or cpu when it hangs outside of tmux

Is there any other information I can help you find? This is definitely stumping me on my side. Should I try to do a bisect or something between 3.0 where it works, and 3.1 where it's broken?

**Comment by ridiculousfish** [comment]
If you are willing to bisect, the would indeed be very useful!

**Comment by cjappl** [comment]
This is what bisect found. The behavior of this commit, both inside and out of tmux is the "hanging" symptom. There is some commit later that introduces the tty issue, which I'll try to bisect now.

The commit before this works 100% as intended, no hanging, no tty issue

```

3bbee06248b073fc30ae5cc8e418c943c8cd6e11 is the first bad commit
commit 3bbee06248b073fc30ae5cc8e418c943c8cd6e11
Author: ridiculousfish <corydoras@ridiculousfish.com>
Date:   Sun Mar 24 14:27:23 2019 -0700

    Introduce the notion of a deferred process

    In a job, a deferred process is the last fish internal process which pipes
    to an external command. Execute the deferred process last; this will allow
    for streaming its output.

 src/exec.cpp | 132 ++++++++++++++++++++++++++++++++++++++++-------------------
 src/io.h     |   4 ++
```

**Comment by cjappl** [comment]
the first commit that has the `Failed to read /dev/tty` issue is this one:
```

f3736e8fdf77652231527383ebbd9d96e71cec4d is the first bad commit
commit f3736e8fdf77652231527383ebbd9d96e71cec4d
Author: ridiculousfish <corydoras@ridiculousfish.com>
Date:   Wed Jun 26 17:20:37 2019 -0700

    fish to claim a job's pgroup if the first process is fish internal

    When executing a job, if the first process is fish internal, then have
    fish claim the job's pgroup.

    The idea here is that the terminal must be owned by a pgroup containing
    the process reading from the terminal. If the first process is fish
    internal (a function or builtin) then the pgroup must contain the fish
    process.

    This is a bit of a workaround of the behavior where the first process that
    executes in a job becomes the process group leader. If there's a deferred
    process, then we will execute processes out of order so the pgroup can be
    wrong. Fix this by setting the process group leader explicitly as fish
    when necessary.

    Fixes #5855

 src/exec.cpp | 39 +++++++++++++++++++++++++++++++++++++++
 1 file changed, 39 insertions(+)
```

**Comment by krobelus** [comment]
Ok the bisect for the hangs matches the old one, see https://github.com/fish-shell/fish-shell/issues/6624#issuecomment-593000805.

This is really strange, the fix seems to work here. Could you try if 3.1.2 works on a different system?

**Comment by cjappl** [comment]
Same behavior on my second machine! Sorry it took a bit for me to get back to you. Everything described above is exactly the same on my second machine (although this machine is running OSX Catalina)

on fish 3.1.2

- hanging outside of tmux
- inside of tmux Failed to read /dev/tty

**Comment by krobelus** [comment]
Is it the same with `eval "git --no-pager log" | env FZF_DEFAULT_OPTS="" fzf`?
Or, better yet, when launching everything without customizations: `env HOME=(mktemp -d) fish`.

**Comment by cjappl** [comment]
So, running the first command in my normal fish results in the same behavior, hang outside of tmux, cannot read /dev/tty inside

running that same command with a clean fish results in the hang both in and out of tmux
