### ISSUE TITLE
scp/ssh tab completion messed up by `sed` alias

### ISSUE THREAD

**Issue by yujiri8** [fish-shell/fish-shell#6772]
Fish version: 3.0.2

$TERM: xterm-256color

Terminal is xfce4-terminal

OS: FreeBSD 12.1-RELEASE-p2 GENERIC amd64

Issue: pressing tab after `scp ` or `ssh ` causes `sed: 1: "s/.* \([A-Za-z0-9._:-]\ ...": \1 not defined in the RE` to be printed twice before it shows the suggestions.

This doesn't happen if I move the completions out of `/usr/local/share/fish/completions/`.

I tried the suggested `sh -c 'env HOME=$(mktemp -d) fish'` and it led me to discovering that the cause is my alias of `sed` in my `config.fish`, which is `function sed; command sed -E $argv; end`. I'm not sure if you still consider this something to be fixed, but I think it's undesirable behavior. Would it be possible to replace the use of `sed` causing this with `command sed`?

**Comment by zanchey** [comment]
Fixed in 3.1.0 with 60248e895f92a37d61.

**Comment by yujiri8** [comment]
Sorry, I forgot to make sure I was using the latest version. But I still see the issue after updating to 3.1.0...

**Comment by faho** [comment]
>But I still see the issue after updating to 3.1.0...

Please make sure you've restarted fish.

**Comment by yujiri8** [comment]
I think I see the issue. The `sed` call is removed on master, but not in 3.1.0. In the Github interface the line is still there if you view tag 3.1.0.

**Comment by krobelus** [comment]
True, for some strange reason https://github.com/fish-shell/fish-shell/commit/2a247c7fe576c40c63ac847361abbcd75823e3ec is not in 3.1.0?

**Comment by faho** [comment]
Ah, it's *that* sed. Yeah, that was removed via 2a247c7fe576c40c63ac847361abbcd75823e3ec, which isn't in 3.1.0.

Tho.... may I suggest just calling your alias something else? Clearly it doesn't behave like `sed`, so why call it that? Just name it `esed`, like `egrep`.

Names are important, and we typically assume that a thing called `sed` acts like `sed`.

**Comment by zanchey** [comment]
Ah, indeed. My apologies.

**Comment by yujiri8** [comment]
> Names are important, and we typically assume that a thing called sed acts like sed.

Well that's a good point, I thought of it as changing the default more than an alias. But adding an extra char to the name is meh. I could call it `se` or something I guess. 'sed extended'
