### ISSUE TITLE
Error initializing fish though ssh

### ISSUE THREAD

**Issue by JalilArfaoui** [fish-shell/fish-shell#9251]
```shell
jalil@g ~> fish --version
fish, version 3.4.1
```

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

```shell
jalil@g ~> uname -a
Linux g 5.15.68 #1-NixOS SMP Thu Sep 15 09:30:08 UTC 2022 x86_64 GNU/Linux
```

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

```
jalil@g ~> sh -c 'env HOME=$(mktemp -d) fish'
Linux g 5.15.68 x86_64
 11:16:56  actif 9 jours  0:00,  3 utilisateurs,  charge moyenne : 0,17, 0,22, 0,21
```

I have an issue with fish when working remotely :

```
ssh 192.168.14.20 -o PreferredAuthentications=password -l jalil
```

I get

```Last login: Fri Sep 30 11:09:15 2022 from 192.168.27.80
error: can not save history
warning-path: Impossible de localiser le dossier data obtenu de $XDG_DATA_HOME: '/.local/share/fish'.
warning-path: L’erreur était 'Permission denied'
warning-path: Veuillez paramétrer $XDG_DATA_HOME à un dossier dans lequel vous avez un accès en écriture.

error: can not save universal variables or functions
warning-path: Impossible de localiser le dossier config obtenu de $XDG_CONFIG_HOME: '/.config/fish'.
warning-path: L’erreur était 'Permission denied'
warning-path: Veuillez paramétrer $XDG_CONFIG_HOME à un dossier dans lequel vous avez un accès en écriture.

/nix/store/p643r4aczmzb0dhyrx3dj592f0s5v7xj-coreutils-9.0/bin/mkdir: cannot create directory ‘/generated_completions’: Permission denied
Bienvenue dans fish, le shell amical et interactif
Type help for instructions on how to use fish
mkdir: impossible de créer le répertoire « /completions »: Permission denied
mkdir: impossible de créer le répertoire « /conf.d »: Permission denied
mkdir: impossible de créer le répertoire « /functions »: Permission denied
warning: An error occurred while redirecting file '/config.fish'
open: Permission denied
```

(Sorry for the french parts)

I’ve checked that I own the mentionned folders and have rw rights on them …

Strange thing is that, after that, if I manually start `fish` command in the opened SSH session, it works well then :

```
jalil@g ~> fish
Linux g 5.15.68 x86_64
 11:20:18  actif 9 jours  0:03,  3 utilisateurs,  charge moyenne : 0,06, 0,14, 0,17
```

No errors and all my config is loaded correctly

Of course, local terminal works fine. I only experience this with SSH. I have the same issue if I connect ssh locally.

What setting am I missing ?

**Comment by faho** [comment]
> I’ve checked that I own the mentionned folders and have rw rights on them …

You checked incorrectly.

The folders look like '/.local/share/fish' - that's in the root of the filesystem.

Which means we are misidentifying your $HOME as "/".

This should be fixed by #8879.

Pleae upgrade to fish 3.5.1 and reply if it doesn't work either.

**Comment by JalilArfaoui** [comment]
I've upgraded to 3.5.1 and I still have the same issue …

I'm not sure 
- where is $XDG_DATA_HOME not set correctly ?
- why `echo $XDG_DATA_HOME` resolves correctly both in SSH and in normal console ?
- why fish only fails in SSH ?

```sh
Linux g 5.15.68 x86_64
00:42:45  actif 12 jours 13:26,  1 utilisateur,  charge moyenne : 1,05, 0,92, 0,93
 ~ > echo $XDG_DATA_HOME
/home/jalil/.local/share
 ~ > ssh localhost
Last login: Fri Sep 30 21:43:20 2022 from 192.168.27.80
error: can not save history
warning-path: Impossible de localiser le dossier data obtenu de $XDG_DATA_HOME: '/.local/share/fish'.
warning-path: L’erreur était 'Permission denied'
warning-path: Veuillez paramétrer $XDG_DATA_HOME à un dossier dans lequel vous avez un accès en écriture.

error: can not save universal variables or functions
warning-path: Impossible de localiser le dossier config obtenu de $XDG_CONFIG_HOME: '/.config/fish'.
warning-path: L’erreur était 'Permission denied'
warning-path: Veuillez paramétrer $XDG_CONFIG_HOME à un dossier dans lequel vous avez un accès en écriture.

/nix/store/qarssrazji0q9xp80xg8shsm2crckfr0-coreutils-9.0/bin/mkdir: cannot create directory ‘/generated_completions’: Permission denied
Bienvenue dans fish, le shell amical et interactif
Type help for instructions on how to use fish
mkdir: impossible de créer le répertoire « /completions »: Permission denied
mkdir: impossible de créer le répertoire « /conf.d »: Permission denied
mkdir: impossible de créer le répertoire « /functions »: Permission denied
warning: An error occurred while redirecting file '/config.fish'
open: Permission denied
jalil@g ~> echo $XDG_DATA_HOME
/home/jalil/.local/share
```

**Comment by faho** [comment]
>why fish only fails in SSH ?

ssh runs on a separate system and has a weird environment - it might have some variables transferred and not others (see ssh's "AcceptEnv", "SendEnv" and "SetEnv" settings in the sshd_config and ssh_config man pages), and those variable settings might belong to an entirely separate user.

>where is $XDG_DATA_HOME not set correctly ?

Fish needs $XDG_X_HOME internally to find the path for some of its files, including config.fish and the generated completions path. For this, it also requires $HOME - the normal $XDG_CONFIG_HOME is defined as $HOME/.config/, so it depends on your home directory. Many things including `sudo` pass along $HOME even when switching to a different user so we need to fix it.

>why echo $XDG_DATA_HOME resolves correctly both in SSH and in normal console ?

Most likely because something somewhere redefines it, e.g. in /etc/fish/config.fish. However this happens too late - it's *after* fish tried to locate the user config file.

I see you're running nix, which has special requirements for its paths, and has special integrations to set its paths - https://github.com/NixOS/nixpkgs/blob/0490b307e5556a8804e710d0c744d29c80fbce48/pkgs/shells/fish/default.nix#L77-L118. It also tries to get you to use babelfish or foreignEnv to "source" bash scripts and get their environment changes into fish. It's possible that this is or is not executed depending on whether the shell is a login shell - ssh typically uses one, local terminals often don't.

What you want to check is something like

```fish
ssh localhost 'echo $USER $HOME $XDG_CONFIG_HOME'
```

which might just be executed early enough that we get the data before it's "fixed" too late.

**Comment by JalilArfaoui** [comment]
```sh
 ~ > ssh localhost 'echo $USER $HOME $XDG_CONFIG_HOME'
error: can not save history
warning-path: Impossible de localiser le dossier data obtenu de $XDG_DATA_HOME: '/.local/share/fish'.
warning-path: L’erreur était 'Permission denied'
warning-path: Veuillez paramétrer $XDG_DATA_HOME à un dossier dans lequel vous avez un accès en écriture.

error: can not save universal variables or functions
warning-path: Impossible de localiser le dossier config obtenu de $XDG_CONFIG_HOME: '/.config/fish'.
warning-path: L’erreur était 'Permission denied'
warning-path: Veuillez paramétrer $XDG_CONFIG_HOME à un dossier dans lequel vous avez un accès en écriture.

Jalil
jalil /home/jalil /.config
 ~ >
 ```

Yes, it seems that despite $HOME is right $XDG_CONFIG_HOME et not correct … not sure why …

**Comment by faho** [comment]
Okay, what does `set -S XDG_CONFIG_HOME` say on the *outer* shell?

**Comment by JalilArfaoui** [comment]
```shell
 ~ > echo $XDG_CONFIG_HOME
/home/jalil/.config
 ~ > set -S XDG_CONFIG_HOME
$XDG_CONFIG_HOME: set in global scope, exportée, with 1 elements
$XDG_CONFIG_HOME[1] : |/home/jalil/.config|
 ~ >
 ```

**Comment by faho** [comment]
I have been unable to reproduce this. It appears something in your config (which can also be bash config, given that this is nix) sets a bogus $XDG_CONFIG_HOME/$XDG_DATA_HOME, and that means fish can't, during startup, find its files, and so it prints an error.

I'm afraid I can't be more specific than that.

**Comment by llitz** [comment]
There's a bug on NixOS, if you define environment.sessionVariables like this
VAR="\${HOME}/anything"

It is parsed verbatim to /etc/pam/environment, instead of using the pam terminology of @{HOME}

To work around this parser bug, simply define the variables without the curly brackets:

VAR="\$HOME/anything"

**Comment by JalilArfaoui** [comment]
Wow ! That did the trick !

Many thanks @llitz ! I would never have found that !
