### ISSUE TITLE
Error 123 (Unsupported use of '=') should set the command like other similar errors do

### ISSUE THREAD

**Issue by mattmc3** [fish-shell/fish-shell#9760]
When running bad fish commands like `echo ${var}`, fish will helpfully tell you that you're typing bash instead of fish syntax and reset the command line for you so you can edit your command and make it right:

<img width="674" alt="Screenshot 2023-04-27 at 9 21 47 PM" src="https://user-images.githubusercontent.com/978625/235032756-03ecd361-3b97-47e0-8890-d2ea29b0bf8a.png">

However, when you type the equals variable assignment syntax `var=123` fish does not behave the same. You have to hit the up arrow to get the command back to fix it.

<img width="682" alt="Screenshot 2023-04-27 at 9 22 10 PM" src="https://user-images.githubusercontent.com/978625/235032758-b5941679-9508-4358-99df-877eff06c71e.png">

Even weirder - if it's multiple commands separated with a semi-colon, it behaves as expected (ie: like other syntax errors):

<img width="650" alt="Screenshot 2023-04-27 at 9 43 45 PM" src="https://user-images.githubusercontent.com/978625/235034415-8519f1bd-4dd8-4077-8e10-71d64c57ed32.png">

And frankly, since fish already knows what the problem is, it might be nice if it just fixed the syntax for you:

```fish
function fix_equals_assignment --on-event fish_postexec
    if test $status = 123
        set --local cmdfix (string replace -ra '\b(\w+)=(\w+)\b' 'set $1 $2' "$argv")
        commandline -r $cmdfix
        commandline -f suppress-autosuggestion
        return 123
    end
end
```

<img width="666" alt="Screenshot 2023-04-27 at 9 46 31 PM" src="https://user-images.githubusercontent.com/978625/235034735-a45fb03c-7acb-4026-840f-54030e03e992.png">

Regardless, this behavior seems inconsistent and [I couldn't make heads or tails of the rust code where the problem seems to be](https://github.com/fish-shell/fish-shell/blob/85d8f2b27fbab75fd94c8c67c556f131c96b4429/fish-rust/src/parse_constants.rs#L446) nor why this error is coded differently than other syntax errors.

Diagnostics -
```fish
$ fish --version
Fish version: 3.6.1
$ uname -a
OS: Darwin CMMV2V19DXCNF 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
$ echo $TERM
xterm-256color
```

**Comment by anmolmathias** [comment]
I can't reproduce this behaviour any more, it seems to have been fixed in one of the releases. We should close this.

**Comment by mattmc3** [comment]
I can still reproduce it on the latest Fish.

The line after an equals error is empty:

```fish
~> fish -N
matt@Orca ~> fish --version
fish, version 4.1.2
matt@Orca ~> abc=123
fish: Unsupported use of '='. In fish, please use 'set abc 123'.

matt@Orca ~ [123]>
```

The line after other syntax errors resets to the command:

```fish
~> fish -N
matt@Orca ~> fish --version
fish, version 4.1.2
matt@Orca ~> set abc 123
matt@Orca ~> echo ${abc}
fish: Variables cannot be bracketed. In fish, please use {$abc}.
echo ${abc}
      ^
matt@Orca ~ [123]> echo ${abc}
```
